const TYPE_COLORS = {
    normal: '#A8A77A',
    fire: '#EE8130',
    water: '#6390F0',
    electric: '#F7D02C',
    grass: '#7AC74C',
    ice: '#96D9D6',
    fighting: '#C22E28',
    poison: '#A33EA1',
    ground: '#E2BF65',
    flying: '#A98FF3',
    psychic: '#F95587',
    bug: '#A6B91A',
    rock: '#B6A136',
    ghost: '#735797',
    dragon: '#6F35FC',
    dark: '#705746',
    steel: '#B7B7CE',
    fairy: '#D685AD'
};

const ALL_TYPES = Object.keys(TYPE_COLORS);

const TYPE_DEFENSE = {
    normal: { weak: ['fighting'], resist: [], immune: ['ghost'] },
    fire: { weak: ['water', 'ground', 'rock'], resist: ['fire', 'grass', 'ice', 'bug', 'steel', 'fairy'], immune: [] },
    water: { weak: ['electric', 'grass'], resist: ['fire', 'water', 'ice', 'steel'], immune: [] },
    electric: { weak: ['ground'], resist: ['electric', 'flying', 'steel'], immune: [] },
    grass: { weak: ['fire', 'ice', 'poison', 'flying', 'bug'], resist: ['water', 'electric', 'grass', 'ground'], immune: [] },
    ice: { weak: ['fire', 'fighting', 'rock', 'steel'], resist: ['ice'], immune: [] },
    fighting: { weak: ['flying', 'psychic', 'fairy'], resist: ['bug', 'rock', 'dark'], immune: [] },
    poison: { weak: ['ground', 'psychic'], resist: ['fighting', 'poison', 'bug', 'grass', 'fairy'], immune: [] },
    ground: { weak: ['water', 'grass', 'ice'], resist: ['poison', 'rock'], immune: ['electric'] },
    flying: { weak: ['electric', 'ice', 'rock'], resist: ['fighting', 'bug', 'grass'], immune: ['ground'] },
    psychic: { weak: ['bug', 'ghost', 'dark'], resist: ['fighting', 'psychic'], immune: [] },
    bug: { weak: ['fire', 'flying', 'rock'], resist: ['fighting', 'ground', 'grass'], immune: [] },
    rock: { weak: ['water', 'grass', 'fighting', 'ground', 'steel'], resist: ['normal', 'fire', 'poison', 'flying'], immune: [] },
    ghost: { weak: ['ghost', 'dark'], resist: ['poison', 'bug'], immune: ['normal', 'fighting'] },
    dragon: { weak: ['ice', 'dragon', 'fairy'], resist: ['fire', 'water', 'electric', 'grass'], immune: [] },
    dark: { weak: ['fighting', 'bug', 'fairy'], resist: ['ghost', 'dark'], immune: ['psychic'] },
    steel: { weak: ['fire', 'fighting', 'ground'], resist: ['normal', 'grass', 'ice', 'flying', 'psychic', 'bug', 'rock', 'dragon', 'steel', 'fairy'], immune: ['poison'] },
    fairy: { weak: ['poison', 'steel'], resist: ['fighting', 'bug', 'dark'], immune: ['dragon'] }
};

function getImageFilename(name) {
    const overrides = {
        "Nidoran♀": "nidoran-f",
        "Nidoran♂": "nidoran-m",
        "Mr. Mime": "mr-mime",
        "Farfetch'd": "farfetchd",
        "Ho-Oh": "ho-oh",
        "Unown": "unown-a"
    };
    return overrides[name] || name.toLowerCase();
}

function calcMatchups(types) {
    const result = {};
    for (const atkType of ALL_TYPES) {
        let multiplier = 1;
        for (const defType of types) {
            const def = TYPE_DEFENSE[defType];
            if (def.immune.includes(atkType)) { multiplier *= 0; }
            else if (def.weak.includes(atkType)) { multiplier *= 2; }
            else if (def.resist.includes(atkType)) { multiplier *= 0.5; }
        }
        result[atkType] = multiplier;
    }
    return result;
}

const POKEMON = [
    // === Generation 1 (Kanto) ===
    // evolutions = total number of stages in this Pokemon's evolution line
    { id: 1, name: "Bulbasaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 2, name: "Ivysaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 3, name: "Venusaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 4, name: "Charmander", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 5, name: "Charmeleon", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 6, name: "Charizard", types: ["fire", "flying"], gen: 1, evolutions: 3 },
    { id: 7, name: "Squirtle", types: ["water"], gen: 1, evolutions: 3 },
    { id: 8, name: "Wartortle", types: ["water"], gen: 1, evolutions: 3 },
    { id: 9, name: "Blastoise", types: ["water"], gen: 1, evolutions: 3 },
    { id: 10, name: "Caterpie", types: ["bug"], gen: 1, evolutions: 3 },
    { id: 11, name: "Metapod", types: ["bug"], gen: 1, evolutions: 3 },
    { id: 12, name: "Butterfree", types: ["bug", "flying"], gen: 1, evolutions: 3 },
    { id: 13, name: "Weedle", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 14, name: "Kakuna", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 15, name: "Beedrill", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 16, name: "Pidgey", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 17, name: "Pidgeotto", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 18, name: "Pidgeot", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 19, name: "Rattata", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 20, name: "Raticate", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 21, name: "Spearow", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 22, name: "Fearow", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 23, name: "Ekans", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 24, name: "Arbok", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 25, name: "Pikachu", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 26, name: "Raichu", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 27, name: "Sandshrew", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 28, name: "Sandslash", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 29, name: "Nidoran♀", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 30, name: "Nidorina", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 31, name: "Nidoqueen", types: ["poison", "ground"], gen: 1, evolutions: 3 },
    { id: 32, name: "Nidoran♂", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 33, name: "Nidorino", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 34, name: "Nidoking", types: ["poison", "ground"], gen: 1, evolutions: 3 },
    { id: 35, name: "Clefairy", types: ["fairy"], gen: 1, evolutions: 3 },
    { id: 36, name: "Clefable", types: ["fairy"], gen: 1, evolutions: 3 },
    { id: 37, name: "Vulpix", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 38, name: "Ninetales", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 39, name: "Jigglypuff", types: ["normal", "fairy"], gen: 1, evolutions: 3 },
    { id: 40, name: "Wigglytuff", types: ["normal", "fairy"], gen: 1, evolutions: 3 },
    { id: 41, name: "Zubat", types: ["poison", "flying"], gen: 1, evolutions: 3 },
    { id: 42, name: "Golbat", types: ["poison", "flying"], gen: 1, evolutions: 3 },
    { id: 43, name: "Oddish", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 44, name: "Gloom", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 45, name: "Vileplume", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 46, name: "Paras", types: ["bug", "grass"], gen: 1, evolutions: 2 },
    { id: 47, name: "Parasect", types: ["bug", "grass"], gen: 1, evolutions: 2 },
    { id: 48, name: "Venonat", types: ["bug", "poison"], gen: 1, evolutions: 2 },
    { id: 49, name: "Venomoth", types: ["bug", "poison"], gen: 1, evolutions: 2 },
    { id: 50, name: "Diglett", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 51, name: "Dugtrio", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 52, name: "Meowth", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 53, name: "Persian", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 54, name: "Psyduck", types: ["water"], gen: 1, evolutions: 2 },
    { id: 55, name: "Golduck", types: ["water"], gen: 1, evolutions: 2 },
    { id: 56, name: "Mankey", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 57, name: "Primeape", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 58, name: "Growlithe", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 59, name: "Arcanine", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 60, name: "Poliwag", types: ["water"], gen: 1, evolutions: 3 },
    { id: 61, name: "Poliwhirl", types: ["water"], gen: 1, evolutions: 3 },
    { id: 62, name: "Poliwrath", types: ["water", "fighting"], gen: 1, evolutions: 3 },
    { id: 63, name: "Abra", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 64, name: "Kadabra", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 65, name: "Alakazam", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 66, name: "Machop", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 67, name: "Machoke", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 68, name: "Machamp", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 69, name: "Bellsprout", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 70, name: "Weepinbell", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 71, name: "Victreebel", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 72, name: "Tentacool", types: ["water", "poison"], gen: 1, evolutions: 2 },
    { id: 73, name: "Tentacruel", types: ["water", "poison"], gen: 1, evolutions: 2 },
    { id: 74, name: "Geodude", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 75, name: "Graveler", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 76, name: "Golem", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 77, name: "Ponyta", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 78, name: "Rapidash", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 79, name: "Slowpoke", types: ["water", "psychic"], gen: 1, evolutions: 3 },
    { id: 80, name: "Slowbro", types: ["water", "psychic"], gen: 1, evolutions: 3 },
    { id: 81, name: "Magnemite", types: ["electric", "steel"], gen: 1, evolutions: 3 },
    { id: 82, name: "Magneton", types: ["electric", "steel"], gen: 1, evolutions: 3 },
    { id: 83, name: "Farfetch'd", types: ["normal", "flying"], gen: 1, evolutions: 1 },
    { id: 84, name: "Doduo", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 85, name: "Dodrio", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 86, name: "Seel", types: ["water"], gen: 1, evolutions: 2 },
    { id: 87, name: "Dewgong", types: ["water", "ice"], gen: 1, evolutions: 2 },
    { id: 88, name: "Grimer", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 89, name: "Muk", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 90, name: "Shellder", types: ["water"], gen: 1, evolutions: 2 },
    { id: 91, name: "Cloyster", types: ["water", "ice"], gen: 1, evolutions: 2 },
    { id: 92, name: "Gastly", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 93, name: "Haunter", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 94, name: "Gengar", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 95, name: "Onix", types: ["rock", "ground"], gen: 1, evolutions: 2 },
    { id: 96, name: "Drowzee", types: ["psychic"], gen: 1, evolutions: 2 },
    { id: 97, name: "Hypno", types: ["psychic"], gen: 1, evolutions: 2 },
    { id: 98, name: "Krabby", types: ["water"], gen: 1, evolutions: 2 },
    { id: 99, name: "Kingler", types: ["water"], gen: 1, evolutions: 2 },
    { id: 100, name: "Voltorb", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 101, name: "Electrode", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 102, name: "Exeggcute", types: ["grass", "psychic"], gen: 1, evolutions: 2 },
    { id: 103, name: "Exeggutor", types: ["grass", "psychic"], gen: 1, evolutions: 2 },
    { id: 104, name: "Cubone", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 105, name: "Marowak", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 106, name: "Hitmonlee", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 107, name: "Hitmonchan", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 108, name: "Lickitung", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 109, name: "Koffing", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 110, name: "Weezing", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 111, name: "Rhyhorn", types: ["ground", "rock"], gen: 1, evolutions: 3 },
    { id: 112, name: "Rhydon", types: ["ground", "rock"], gen: 1, evolutions: 3 },
    { id: 113, name: "Chansey", types: ["normal"], gen: 1, evolutions: 3 },
    { id: 114, name: "Tangela", types: ["grass"], gen: 1, evolutions: 2 },
    { id: 115, name: "Kangaskhan", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 116, name: "Horsea", types: ["water"], gen: 1, evolutions: 3 },
    { id: 117, name: "Seadra", types: ["water"], gen: 1, evolutions: 3 },
    { id: 118, name: "Goldeen", types: ["water"], gen: 1, evolutions: 2 },
    { id: 119, name: "Seaking", types: ["water"], gen: 1, evolutions: 2 },
    { id: 120, name: "Staryu", types: ["water"], gen: 1, evolutions: 2 },
    { id: 121, name: "Starmie", types: ["water", "psychic"], gen: 1, evolutions: 2 },
    { id: 122, name: "Mr. Mime", types: ["psychic", "fairy"], gen: 1, evolutions: 2 },
    { id: 123, name: "Scyther", types: ["bug", "flying"], gen: 1, evolutions: 2 },
    { id: 124, name: "Jynx", types: ["ice", "psychic"], gen: 1, evolutions: 2 },
    { id: 125, name: "Electabuzz", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 126, name: "Magmar", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 127, name: "Pinsir", types: ["bug"], gen: 1, evolutions: 1 },
    { id: 128, name: "Tauros", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 129, name: "Magikarp", types: ["water"], gen: 1, evolutions: 2 },
    { id: 130, name: "Gyarados", types: ["water", "flying"], gen: 1, evolutions: 2 },
    { id: 131, name: "Lapras", types: ["water", "ice"], gen: 1, evolutions: 1 },
    { id: 132, name: "Ditto", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 133, name: "Eevee", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 134, name: "Vaporeon", types: ["water"], gen: 1, evolutions: 2 },
    { id: 135, name: "Jolteon", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 136, name: "Flareon", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 137, name: "Porygon", types: ["normal"], gen: 1, evolutions: 3 },
    { id: 138, name: "Omanyte", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 139, name: "Omastar", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 140, name: "Kabuto", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 141, name: "Kabutops", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 142, name: "Aerodactyl", types: ["rock", "flying"], gen: 1, evolutions: 1 },
    { id: 143, name: "Snorlax", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 144, name: "Articuno", types: ["ice", "flying"], gen: 1, evolutions: 1 },
    { id: 145, name: "Zapdos", types: ["electric", "flying"], gen: 1, evolutions: 1 },
    { id: 146, name: "Moltres", types: ["fire", "flying"], gen: 1, evolutions: 1 },
    { id: 147, name: "Dratini", types: ["dragon"], gen: 1, evolutions: 3 },
    { id: 148, name: "Dragonair", types: ["dragon"], gen: 1, evolutions: 3 },
    { id: 149, name: "Dragonite", types: ["dragon", "flying"], gen: 1, evolutions: 3 },
    { id: 150, name: "Mewtwo", types: ["psychic"], gen: 1, evolutions: 1 },
    { id: 151, name: "Mew", types: ["psychic"], gen: 1, evolutions: 1 },

    // === Generation 2 (Johto) ===
    { id: 152, name: "Chikorita", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 153, name: "Bayleef", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 154, name: "Meganium", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 155, name: "Cyndaquil", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 156, name: "Quilava", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 157, name: "Typhlosion", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 158, name: "Totodile", types: ["water"], gen: 2, evolutions: 3 },
    { id: 159, name: "Croconaw", types: ["water"], gen: 2, evolutions: 3 },
    { id: 160, name: "Feraligatr", types: ["water"], gen: 2, evolutions: 3 },
    { id: 161, name: "Sentret", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 162, name: "Furret", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 163, name: "Hoothoot", types: ["normal", "flying"], gen: 2, evolutions: 2 },
    { id: 164, name: "Noctowl", types: ["normal", "flying"], gen: 2, evolutions: 2 },
    { id: 165, name: "Ledyba", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 166, name: "Ledian", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 167, name: "Spinarak", types: ["bug", "poison"], gen: 2, evolutions: 2 },
    { id: 168, name: "Ariados", types: ["bug", "poison"], gen: 2, evolutions: 2 },
    { id: 169, name: "Crobat", types: ["poison", "flying"], gen: 2, evolutions: 3 },
    { id: 170, name: "Chinchou", types: ["water", "electric"], gen: 2, evolutions: 2 },
    { id: 171, name: "Lanturn", types: ["water", "electric"], gen: 2, evolutions: 2 },
    { id: 172, name: "Pichu", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 173, name: "Cleffa", types: ["fairy"], gen: 2, evolutions: 3 },
    { id: 174, name: "Igglybuff", types: ["normal", "fairy"], gen: 2, evolutions: 3 },
    { id: 175, name: "Togepi", types: ["fairy"], gen: 2, evolutions: 3 },
    { id: 176, name: "Togetic", types: ["fairy", "flying"], gen: 2, evolutions: 3 },
    { id: 177, name: "Natu", types: ["psychic", "flying"], gen: 2, evolutions: 2 },
    { id: 178, name: "Xatu", types: ["psychic", "flying"], gen: 2, evolutions: 2 },
    { id: 179, name: "Mareep", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 180, name: "Flaaffy", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 181, name: "Ampharos", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 182, name: "Bellossom", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 183, name: "Marill", types: ["water", "fairy"], gen: 2, evolutions: 3 },
    { id: 184, name: "Azumarill", types: ["water", "fairy"], gen: 2, evolutions: 3 },
    { id: 185, name: "Sudowoodo", types: ["rock"], gen: 2, evolutions: 2 },
    { id: 186, name: "Politoed", types: ["water"], gen: 2, evolutions: 3 },
    { id: 187, name: "Hoppip", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 188, name: "Skiploom", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 189, name: "Jumpluff", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 190, name: "Aipom", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 191, name: "Sunkern", types: ["grass"], gen: 2, evolutions: 2 },
    { id: 192, name: "Sunflora", types: ["grass"], gen: 2, evolutions: 2 },
    { id: 193, name: "Yanma", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 194, name: "Wooper", types: ["water", "ground"], gen: 2, evolutions: 2 },
    { id: 195, name: "Quagsire", types: ["water", "ground"], gen: 2, evolutions: 2 },
    { id: 196, name: "Espeon", types: ["psychic"], gen: 2, evolutions: 2 },
    { id: 197, name: "Umbreon", types: ["dark"], gen: 2, evolutions: 2 },
    { id: 198, name: "Murkrow", types: ["dark", "flying"], gen: 2, evolutions: 2 },
    { id: 199, name: "Slowking", types: ["water", "psychic"], gen: 2, evolutions: 3 },
    { id: 200, name: "Misdreavus", types: ["ghost"], gen: 2, evolutions: 2 },
    { id: 201, name: "Unown", types: ["psychic"], gen: 2, evolutions: 1 },
    { id: 202, name: "Wobbuffet", types: ["psychic"], gen: 2, evolutions: 2 },
    { id: 203, name: "Girafarig", types: ["normal", "psychic"], gen: 2, evolutions: 1 },
    { id: 204, name: "Pineco", types: ["bug"], gen: 2, evolutions: 2 },
    { id: 205, name: "Forretress", types: ["bug", "steel"], gen: 2, evolutions: 2 },
    { id: 206, name: "Dunsparce", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 207, name: "Gligar", types: ["ground", "flying"], gen: 2, evolutions: 2 },
    { id: 208, name: "Steelix", types: ["steel", "ground"], gen: 2, evolutions: 2 },
    { id: 209, name: "Snubbull", types: ["fairy"], gen: 2, evolutions: 2 },
    { id: 210, name: "Granbull", types: ["fairy"], gen: 2, evolutions: 2 },
    { id: 211, name: "Qwilfish", types: ["water", "poison"], gen: 2, evolutions: 1 },
    { id: 212, name: "Scizor", types: ["bug", "steel"], gen: 2, evolutions: 2 },
    { id: 213, name: "Shuckle", types: ["bug", "rock"], gen: 2, evolutions: 1 },
    { id: 214, name: "Heracross", types: ["bug", "fighting"], gen: 2, evolutions: 1 },
    { id: 215, name: "Sneasel", types: ["dark", "ice"], gen: 2, evolutions: 2 },
    { id: 216, name: "Teddiursa", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 217, name: "Ursaring", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 218, name: "Slugma", types: ["fire"], gen: 2, evolutions: 2 },
    { id: 219, name: "Magcargo", types: ["fire", "rock"], gen: 2, evolutions: 2 },
    { id: 220, name: "Swinub", types: ["ice", "ground"], gen: 2, evolutions: 3 },
    { id: 221, name: "Piloswine", types: ["ice", "ground"], gen: 2, evolutions: 3 },
    { id: 222, name: "Corsola", types: ["water", "rock"], gen: 2, evolutions: 1 },
    { id: 223, name: "Remoraid", types: ["water"], gen: 2, evolutions: 2 },
    { id: 224, name: "Octillery", types: ["water"], gen: 2, evolutions: 2 },
    { id: 225, name: "Delibird", types: ["ice", "flying"], gen: 2, evolutions: 1 },
    { id: 226, name: "Mantine", types: ["water", "flying"], gen: 2, evolutions: 2 },
    { id: 227, name: "Skarmory", types: ["steel", "flying"], gen: 2, evolutions: 1 },
    { id: 228, name: "Houndour", types: ["dark", "fire"], gen: 2, evolutions: 2 },
    { id: 229, name: "Houndoom", types: ["dark", "fire"], gen: 2, evolutions: 2 },
    { id: 230, name: "Kingdra", types: ["water", "dragon"], gen: 2, evolutions: 3 },
    { id: 231, name: "Phanpy", types: ["ground"], gen: 2, evolutions: 2 },
    { id: 232, name: "Donphan", types: ["ground"], gen: 2, evolutions: 2 },
    { id: 233, name: "Porygon2", types: ["normal"], gen: 2, evolutions: 3 },
    { id: 234, name: "Stantler", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 235, name: "Smeargle", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 236, name: "Tyrogue", types: ["fighting"], gen: 2, evolutions: 2 },
    { id: 237, name: "Hitmontop", types: ["fighting"], gen: 2, evolutions: 2 },
    { id: 238, name: "Smoochum", types: ["ice", "psychic"], gen: 2, evolutions: 2 },
    { id: 239, name: "Elekid", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 240, name: "Magby", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 241, name: "Miltank", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 242, name: "Blissey", types: ["normal"], gen: 2, evolutions: 3 },
    { id: 243, name: "Raikou", types: ["electric"], gen: 2, evolutions: 1 },
    { id: 244, name: "Entei", types: ["fire"], gen: 2, evolutions: 1 },
    { id: 245, name: "Suicune", types: ["water"], gen: 2, evolutions: 1 },
    { id: 246, name: "Larvitar", types: ["rock", "ground"], gen: 2, evolutions: 3 },
    { id: 247, name: "Pupitar", types: ["rock", "ground"], gen: 2, evolutions: 3 },
    { id: 248, name: "Tyranitar", types: ["rock", "dark"], gen: 2, evolutions: 3 },
    { id: 249, name: "Lugia", types: ["psychic", "flying"], gen: 2, evolutions: 1 },
    { id: 250, name: "Ho-Oh", types: ["fire", "flying"], gen: 2, evolutions: 1 },
    { id: 251, name: "Celebi", types: ["psychic", "grass"], gen: 2, evolutions: 1 }
];
