const TYPE_COLORS = {
    normal: '#A8A77A',
    fire: '#EE8130',
    water: '#6390F0',
    electric: '#F7D02C',
    grass: '#7AC74C',
    ice: '#96D9D6',
    fighting: '#C22E28',
    poison: '#A33EA1',
    ground: '#E2BF65',
    flying: '#A98FF3',
    psychic: '#F95587',
    bug: '#A6B91A',
    rock: '#B6A136',
    ghost: '#735797',
    dragon: '#6F35FC',
    dark: '#705746',
    steel: '#B7B7CE',
    fairy: '#D685AD'
};

const ALL_TYPES = Object.keys(TYPE_COLORS);

const TYPE_DEFENSE = {
    normal: { weak: ['fighting'], resist: [], immune: ['ghost'] },
    fire: { weak: ['water', 'ground', 'rock'], resist: ['fire', 'grass', 'ice', 'bug', 'steel', 'fairy'], immune: [] },
    water: { weak: ['electric', 'grass'], resist: ['fire', 'water', 'ice', 'steel'], immune: [] },
    electric: { weak: ['ground'], resist: ['electric', 'flying', 'steel'], immune: [] },
    grass: { weak: ['fire', 'ice', 'poison', 'flying', 'bug'], resist: ['water', 'electric', 'grass', 'ground'], immune: [] },
    ice: { weak: ['fire', 'fighting', 'rock', 'steel'], resist: ['ice'], immune: [] },
    fighting: { weak: ['flying', 'psychic', 'fairy'], resist: ['bug', 'rock', 'dark'], immune: [] },
    poison: { weak: ['ground', 'psychic'], resist: ['fighting', 'poison', 'bug', 'grass', 'fairy'], immune: [] },
    ground: { weak: ['water', 'grass', 'ice'], resist: ['poison', 'rock'], immune: ['electric'] },
    flying: { weak: ['electric', 'ice', 'rock'], resist: ['fighting', 'bug', 'grass'], immune: ['ground'] },
    psychic: { weak: ['bug', 'ghost', 'dark'], resist: ['fighting', 'psychic'], immune: [] },
    bug: { weak: ['fire', 'flying', 'rock'], resist: ['fighting', 'ground', 'grass'], immune: [] },
    rock: { weak: ['water', 'grass', 'fighting', 'ground', 'steel'], resist: ['normal', 'fire', 'poison', 'flying'], immune: [] },
    ghost: { weak: ['ghost', 'dark'], resist: ['poison', 'bug'], immune: ['normal', 'fighting'] },
    dragon: { weak: ['ice', 'dragon', 'fairy'], resist: ['fire', 'water', 'electric', 'grass'], immune: [] },
    dark: { weak: ['fighting', 'bug', 'fairy'], resist: ['ghost', 'dark'], immune: ['psychic'] },
    steel: { weak: ['fire', 'fighting', 'ground'], resist: ['normal', 'grass', 'ice', 'flying', 'psychic', 'bug', 'rock', 'dragon', 'steel', 'fairy'], immune: ['poison'] },
    fairy: { weak: ['poison', 'steel'], resist: ['fighting', 'bug', 'dark'], immune: ['dragon'] }
};

function getImageFilename(name) {
    const overrides = {
        "Nidoran♀": "nidoran-f",
        "Nidoran♂": "nidoran-m",
        "Mr. Mime": "mr-mime",
        "Farfetch'd": "farfetchd",
        "Ho-Oh": "ho-oh",
        "Unown": "unown-a",
        "Mime Jr.": "mime-jr",
        "Deoxys": "deoxys-normal",
        "Burmy": "burmy-plant",
        "Wormadam": "wormadam-plant",
        "Mothim": "mothim-plant",
        "Cherrim": "cherrim-overcast",
        "Shellos": "shellos-west",
        "Gastrodon": "gastrodon-west",
        "Giratina": "giratina-altered",
        "Shaymin": "shaymin-land",
        "Arceus": "arceus-normal",
        "Basculin": "basculin-red-striped",
        "Darmanitan": "darmanitan-standard",
        "Deerling": "deerling-spring",
        "Sawsbuck": "sawsbuck-spring",
        "Tornadus": "tornadus-incarnate",
        "Thundurus": "thundurus-incarnate",
        "Landorus": "landorus-incarnate",
        "Keldeo": "keldeo-ordinary",
        "Meloetta": "meloetta-aria",
        "Flabébé": "flabebe-red",
        "Floette": "floette-red",
        "Florges": "florges-red",
        "Scatterbug": "scatterbug-icy-snow",
        "Spewpa": "spewpa-icy-snow",
        "Vivillon": "vivillon-meadow",
        "Furfrou": "furfrou-natural",
        "Meowstic": "meowstic-male",
        "Aegislash": "aegislash-shield",
        "Pumpkaboo": "pumpkaboo-average",
        "Gourgeist": "gourgeist-average",
        "Xerneas": "xerneas-active",
        "Type: Null": "type-null",
        "Silvally": "silvally-normal",
        "Oricorio": "oricorio-baile",
        "Lycanroc": "lycanroc-midday",
        "Wishiwashi": "wishiwashi-solo",
        "Minior": "minior-red-meteor",
        "Mimikyu": "mimikyu-disguised",
        "Tapu Koko": "tapu-koko",
        "Tapu Lele": "tapu-lele",
        "Tapu Bulu": "tapu-bulu",
        "Tapu Fini": "tapu-fini",
        "Toxtricity": "toxtricity-amped",
        "Sinistea": "sinistea-phony",
        "Polteageist": "polteageist-phony",
        "Eiscue": "eiscue-ice",
        "Indeedee": "indeedee-male",
        "Morpeko": "morpeko-full-belly",
        "Zacian": "zacian-hero",
        "Zamazenta": "zamazenta-hero",
        "Sirfetch\u2019d": "sirfetchd",
        "Mr. Rime": "mr-rime"
    };
    return overrides[name] || name.toLowerCase();
}

function calcMatchups(types) {
    const result = {};
    for (const atkType of ALL_TYPES) {
        let multiplier = 1;
        for (const defType of types) {
            const def = TYPE_DEFENSE[defType];
            if (def.immune.includes(atkType)) { multiplier *= 0; }
            else if (def.weak.includes(atkType)) { multiplier *= 2; }
            else if (def.resist.includes(atkType)) { multiplier *= 0.5; }
        }
        result[atkType] = multiplier;
    }
    return result;
}

const POKEMON = [
    // === Generation 1 (Kanto) ===
    // evolutions = total number of stages in this Pokemon's evolution line
    { id: 1, name: "Bulbasaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 2, name: "Ivysaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 3, name: "Venusaur", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 4, name: "Charmander", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 5, name: "Charmeleon", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 6, name: "Charizard", types: ["fire", "flying"], gen: 1, evolutions: 3 },
    { id: 7, name: "Squirtle", types: ["water"], gen: 1, evolutions: 3 },
    { id: 8, name: "Wartortle", types: ["water"], gen: 1, evolutions: 3 },
    { id: 9, name: "Blastoise", types: ["water"], gen: 1, evolutions: 3 },
    { id: 10, name: "Caterpie", types: ["bug"], gen: 1, evolutions: 3 },
    { id: 11, name: "Metapod", types: ["bug"], gen: 1, evolutions: 3 },
    { id: 12, name: "Butterfree", types: ["bug", "flying"], gen: 1, evolutions: 3 },
    { id: 13, name: "Weedle", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 14, name: "Kakuna", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 15, name: "Beedrill", types: ["bug", "poison"], gen: 1, evolutions: 3 },
    { id: 16, name: "Pidgey", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 17, name: "Pidgeotto", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 18, name: "Pidgeot", types: ["normal", "flying"], gen: 1, evolutions: 3 },
    { id: 19, name: "Rattata", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 20, name: "Raticate", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 21, name: "Spearow", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 22, name: "Fearow", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 23, name: "Ekans", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 24, name: "Arbok", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 25, name: "Pikachu", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 26, name: "Raichu", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 27, name: "Sandshrew", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 28, name: "Sandslash", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 29, name: "Nidoran♀", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 30, name: "Nidorina", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 31, name: "Nidoqueen", types: ["poison", "ground"], gen: 1, evolutions: 3 },
    { id: 32, name: "Nidoran♂", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 33, name: "Nidorino", types: ["poison"], gen: 1, evolutions: 3 },
    { id: 34, name: "Nidoking", types: ["poison", "ground"], gen: 1, evolutions: 3 },
    { id: 35, name: "Clefairy", types: ["fairy"], gen: 1, evolutions: 3 },
    { id: 36, name: "Clefable", types: ["fairy"], gen: 1, evolutions: 3 },
    { id: 37, name: "Vulpix", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 38, name: "Ninetales", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 39, name: "Jigglypuff", types: ["normal", "fairy"], gen: 1, evolutions: 3 },
    { id: 40, name: "Wigglytuff", types: ["normal", "fairy"], gen: 1, evolutions: 3 },
    { id: 41, name: "Zubat", types: ["poison", "flying"], gen: 1, evolutions: 3 },
    { id: 42, name: "Golbat", types: ["poison", "flying"], gen: 1, evolutions: 3 },
    { id: 43, name: "Oddish", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 44, name: "Gloom", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 45, name: "Vileplume", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 46, name: "Paras", types: ["bug", "grass"], gen: 1, evolutions: 2 },
    { id: 47, name: "Parasect", types: ["bug", "grass"], gen: 1, evolutions: 2 },
    { id: 48, name: "Venonat", types: ["bug", "poison"], gen: 1, evolutions: 2 },
    { id: 49, name: "Venomoth", types: ["bug", "poison"], gen: 1, evolutions: 2 },
    { id: 50, name: "Diglett", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 51, name: "Dugtrio", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 52, name: "Meowth", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 53, name: "Persian", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 54, name: "Psyduck", types: ["water"], gen: 1, evolutions: 2 },
    { id: 55, name: "Golduck", types: ["water"], gen: 1, evolutions: 2 },
    { id: 56, name: "Mankey", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 57, name: "Primeape", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 58, name: "Growlithe", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 59, name: "Arcanine", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 60, name: "Poliwag", types: ["water"], gen: 1, evolutions: 3 },
    { id: 61, name: "Poliwhirl", types: ["water"], gen: 1, evolutions: 3 },
    { id: 62, name: "Poliwrath", types: ["water", "fighting"], gen: 1, evolutions: 3 },
    { id: 63, name: "Abra", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 64, name: "Kadabra", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 65, name: "Alakazam", types: ["psychic"], gen: 1, evolutions: 3 },
    { id: 66, name: "Machop", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 67, name: "Machoke", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 68, name: "Machamp", types: ["fighting"], gen: 1, evolutions: 3 },
    { id: 69, name: "Bellsprout", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 70, name: "Weepinbell", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 71, name: "Victreebel", types: ["grass", "poison"], gen: 1, evolutions: 3 },
    { id: 72, name: "Tentacool", types: ["water", "poison"], gen: 1, evolutions: 2 },
    { id: 73, name: "Tentacruel", types: ["water", "poison"], gen: 1, evolutions: 2 },
    { id: 74, name: "Geodude", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 75, name: "Graveler", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 76, name: "Golem", types: ["rock", "ground"], gen: 1, evolutions: 3 },
    { id: 77, name: "Ponyta", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 78, name: "Rapidash", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 79, name: "Slowpoke", types: ["water", "psychic"], gen: 1, evolutions: 3 },
    { id: 80, name: "Slowbro", types: ["water", "psychic"], gen: 1, evolutions: 3 },
    { id: 81, name: "Magnemite", types: ["electric", "steel"], gen: 1, evolutions: 3 },
    { id: 82, name: "Magneton", types: ["electric", "steel"], gen: 1, evolutions: 3 },
    { id: 83, name: "Farfetch'd", types: ["normal", "flying"], gen: 1, evolutions: 1 },
    { id: 84, name: "Doduo", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 85, name: "Dodrio", types: ["normal", "flying"], gen: 1, evolutions: 2 },
    { id: 86, name: "Seel", types: ["water"], gen: 1, evolutions: 2 },
    { id: 87, name: "Dewgong", types: ["water", "ice"], gen: 1, evolutions: 2 },
    { id: 88, name: "Grimer", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 89, name: "Muk", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 90, name: "Shellder", types: ["water"], gen: 1, evolutions: 2 },
    { id: 91, name: "Cloyster", types: ["water", "ice"], gen: 1, evolutions: 2 },
    { id: 92, name: "Gastly", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 93, name: "Haunter", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 94, name: "Gengar", types: ["ghost", "poison"], gen: 1, evolutions: 3 },
    { id: 95, name: "Onix", types: ["rock", "ground"], gen: 1, evolutions: 2 },
    { id: 96, name: "Drowzee", types: ["psychic"], gen: 1, evolutions: 2 },
    { id: 97, name: "Hypno", types: ["psychic"], gen: 1, evolutions: 2 },
    { id: 98, name: "Krabby", types: ["water"], gen: 1, evolutions: 2 },
    { id: 99, name: "Kingler", types: ["water"], gen: 1, evolutions: 2 },
    { id: 100, name: "Voltorb", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 101, name: "Electrode", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 102, name: "Exeggcute", types: ["grass", "psychic"], gen: 1, evolutions: 2 },
    { id: 103, name: "Exeggutor", types: ["grass", "psychic"], gen: 1, evolutions: 2 },
    { id: 104, name: "Cubone", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 105, name: "Marowak", types: ["ground"], gen: 1, evolutions: 2 },
    { id: 106, name: "Hitmonlee", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 107, name: "Hitmonchan", types: ["fighting"], gen: 1, evolutions: 2 },
    { id: 108, name: "Lickitung", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 109, name: "Koffing", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 110, name: "Weezing", types: ["poison"], gen: 1, evolutions: 2 },
    { id: 111, name: "Rhyhorn", types: ["ground", "rock"], gen: 1, evolutions: 3 },
    { id: 112, name: "Rhydon", types: ["ground", "rock"], gen: 1, evolutions: 3 },
    { id: 113, name: "Chansey", types: ["normal"], gen: 1, evolutions: 3 },
    { id: 114, name: "Tangela", types: ["grass"], gen: 1, evolutions: 2 },
    { id: 115, name: "Kangaskhan", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 116, name: "Horsea", types: ["water"], gen: 1, evolutions: 3 },
    { id: 117, name: "Seadra", types: ["water"], gen: 1, evolutions: 3 },
    { id: 118, name: "Goldeen", types: ["water"], gen: 1, evolutions: 2 },
    { id: 119, name: "Seaking", types: ["water"], gen: 1, evolutions: 2 },
    { id: 120, name: "Staryu", types: ["water"], gen: 1, evolutions: 2 },
    { id: 121, name: "Starmie", types: ["water", "psychic"], gen: 1, evolutions: 2 },
    { id: 122, name: "Mr. Mime", types: ["psychic", "fairy"], gen: 1, evolutions: 2 },
    { id: 123, name: "Scyther", types: ["bug", "flying"], gen: 1, evolutions: 2 },
    { id: 124, name: "Jynx", types: ["ice", "psychic"], gen: 1, evolutions: 2 },
    { id: 125, name: "Electabuzz", types: ["electric"], gen: 1, evolutions: 3 },
    { id: 126, name: "Magmar", types: ["fire"], gen: 1, evolutions: 3 },
    { id: 127, name: "Pinsir", types: ["bug"], gen: 1, evolutions: 1 },
    { id: 128, name: "Tauros", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 129, name: "Magikarp", types: ["water"], gen: 1, evolutions: 2 },
    { id: 130, name: "Gyarados", types: ["water", "flying"], gen: 1, evolutions: 2 },
    { id: 131, name: "Lapras", types: ["water", "ice"], gen: 1, evolutions: 1 },
    { id: 132, name: "Ditto", types: ["normal"], gen: 1, evolutions: 1 },
    { id: 133, name: "Eevee", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 134, name: "Vaporeon", types: ["water"], gen: 1, evolutions: 2 },
    { id: 135, name: "Jolteon", types: ["electric"], gen: 1, evolutions: 2 },
    { id: 136, name: "Flareon", types: ["fire"], gen: 1, evolutions: 2 },
    { id: 137, name: "Porygon", types: ["normal"], gen: 1, evolutions: 3 },
    { id: 138, name: "Omanyte", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 139, name: "Omastar", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 140, name: "Kabuto", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 141, name: "Kabutops", types: ["rock", "water"], gen: 1, evolutions: 2 },
    { id: 142, name: "Aerodactyl", types: ["rock", "flying"], gen: 1, evolutions: 1 },
    { id: 143, name: "Snorlax", types: ["normal"], gen: 1, evolutions: 2 },
    { id: 144, name: "Articuno", types: ["ice", "flying"], gen: 1, evolutions: 1 },
    { id: 145, name: "Zapdos", types: ["electric", "flying"], gen: 1, evolutions: 1 },
    { id: 146, name: "Moltres", types: ["fire", "flying"], gen: 1, evolutions: 1 },
    { id: 147, name: "Dratini", types: ["dragon"], gen: 1, evolutions: 3 },
    { id: 148, name: "Dragonair", types: ["dragon"], gen: 1, evolutions: 3 },
    { id: 149, name: "Dragonite", types: ["dragon", "flying"], gen: 1, evolutions: 3 },
    { id: 150, name: "Mewtwo", types: ["psychic"], gen: 1, evolutions: 1 },
    { id: 151, name: "Mew", types: ["psychic"], gen: 1, evolutions: 1 },

    // === Generation 2 (Johto) ===
    { id: 152, name: "Chikorita", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 153, name: "Bayleef", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 154, name: "Meganium", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 155, name: "Cyndaquil", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 156, name: "Quilava", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 157, name: "Typhlosion", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 158, name: "Totodile", types: ["water"], gen: 2, evolutions: 3 },
    { id: 159, name: "Croconaw", types: ["water"], gen: 2, evolutions: 3 },
    { id: 160, name: "Feraligatr", types: ["water"], gen: 2, evolutions: 3 },
    { id: 161, name: "Sentret", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 162, name: "Furret", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 163, name: "Hoothoot", types: ["normal", "flying"], gen: 2, evolutions: 2 },
    { id: 164, name: "Noctowl", types: ["normal", "flying"], gen: 2, evolutions: 2 },
    { id: 165, name: "Ledyba", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 166, name: "Ledian", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 167, name: "Spinarak", types: ["bug", "poison"], gen: 2, evolutions: 2 },
    { id: 168, name: "Ariados", types: ["bug", "poison"], gen: 2, evolutions: 2 },
    { id: 169, name: "Crobat", types: ["poison", "flying"], gen: 2, evolutions: 3 },
    { id: 170, name: "Chinchou", types: ["water", "electric"], gen: 2, evolutions: 2 },
    { id: 171, name: "Lanturn", types: ["water", "electric"], gen: 2, evolutions: 2 },
    { id: 172, name: "Pichu", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 173, name: "Cleffa", types: ["fairy"], gen: 2, evolutions: 3 },
    { id: 174, name: "Igglybuff", types: ["normal", "fairy"], gen: 2, evolutions: 3 },
    { id: 175, name: "Togepi", types: ["fairy"], gen: 2, evolutions: 3 },
    { id: 176, name: "Togetic", types: ["fairy", "flying"], gen: 2, evolutions: 3 },
    { id: 177, name: "Natu", types: ["psychic", "flying"], gen: 2, evolutions: 2 },
    { id: 178, name: "Xatu", types: ["psychic", "flying"], gen: 2, evolutions: 2 },
    { id: 179, name: "Mareep", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 180, name: "Flaaffy", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 181, name: "Ampharos", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 182, name: "Bellossom", types: ["grass"], gen: 2, evolutions: 3 },
    { id: 183, name: "Marill", types: ["water", "fairy"], gen: 2, evolutions: 3 },
    { id: 184, name: "Azumarill", types: ["water", "fairy"], gen: 2, evolutions: 3 },
    { id: 185, name: "Sudowoodo", types: ["rock"], gen: 2, evolutions: 2 },
    { id: 186, name: "Politoed", types: ["water"], gen: 2, evolutions: 3 },
    { id: 187, name: "Hoppip", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 188, name: "Skiploom", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 189, name: "Jumpluff", types: ["grass", "flying"], gen: 2, evolutions: 3 },
    { id: 190, name: "Aipom", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 191, name: "Sunkern", types: ["grass"], gen: 2, evolutions: 2 },
    { id: 192, name: "Sunflora", types: ["grass"], gen: 2, evolutions: 2 },
    { id: 193, name: "Yanma", types: ["bug", "flying"], gen: 2, evolutions: 2 },
    { id: 194, name: "Wooper", types: ["water", "ground"], gen: 2, evolutions: 2 },
    { id: 195, name: "Quagsire", types: ["water", "ground"], gen: 2, evolutions: 2 },
    { id: 196, name: "Espeon", types: ["psychic"], gen: 2, evolutions: 2 },
    { id: 197, name: "Umbreon", types: ["dark"], gen: 2, evolutions: 2 },
    { id: 198, name: "Murkrow", types: ["dark", "flying"], gen: 2, evolutions: 2 },
    { id: 199, name: "Slowking", types: ["water", "psychic"], gen: 2, evolutions: 3 },
    { id: 200, name: "Misdreavus", types: ["ghost"], gen: 2, evolutions: 2 },
    { id: 201, name: "Unown", types: ["psychic"], gen: 2, evolutions: 1 },
    { id: 202, name: "Wobbuffet", types: ["psychic"], gen: 2, evolutions: 2 },
    { id: 203, name: "Girafarig", types: ["normal", "psychic"], gen: 2, evolutions: 1 },
    { id: 204, name: "Pineco", types: ["bug"], gen: 2, evolutions: 2 },
    { id: 205, name: "Forretress", types: ["bug", "steel"], gen: 2, evolutions: 2 },
    { id: 206, name: "Dunsparce", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 207, name: "Gligar", types: ["ground", "flying"], gen: 2, evolutions: 2 },
    { id: 208, name: "Steelix", types: ["steel", "ground"], gen: 2, evolutions: 2 },
    { id: 209, name: "Snubbull", types: ["fairy"], gen: 2, evolutions: 2 },
    { id: 210, name: "Granbull", types: ["fairy"], gen: 2, evolutions: 2 },
    { id: 211, name: "Qwilfish", types: ["water", "poison"], gen: 2, evolutions: 1 },
    { id: 212, name: "Scizor", types: ["bug", "steel"], gen: 2, evolutions: 2 },
    { id: 213, name: "Shuckle", types: ["bug", "rock"], gen: 2, evolutions: 1 },
    { id: 214, name: "Heracross", types: ["bug", "fighting"], gen: 2, evolutions: 1 },
    { id: 215, name: "Sneasel", types: ["dark", "ice"], gen: 2, evolutions: 2 },
    { id: 216, name: "Teddiursa", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 217, name: "Ursaring", types: ["normal"], gen: 2, evolutions: 2 },
    { id: 218, name: "Slugma", types: ["fire"], gen: 2, evolutions: 2 },
    { id: 219, name: "Magcargo", types: ["fire", "rock"], gen: 2, evolutions: 2 },
    { id: 220, name: "Swinub", types: ["ice", "ground"], gen: 2, evolutions: 3 },
    { id: 221, name: "Piloswine", types: ["ice", "ground"], gen: 2, evolutions: 3 },
    { id: 222, name: "Corsola", types: ["water", "rock"], gen: 2, evolutions: 1 },
    { id: 223, name: "Remoraid", types: ["water"], gen: 2, evolutions: 2 },
    { id: 224, name: "Octillery", types: ["water"], gen: 2, evolutions: 2 },
    { id: 225, name: "Delibird", types: ["ice", "flying"], gen: 2, evolutions: 1 },
    { id: 226, name: "Mantine", types: ["water", "flying"], gen: 2, evolutions: 2 },
    { id: 227, name: "Skarmory", types: ["steel", "flying"], gen: 2, evolutions: 1 },
    { id: 228, name: "Houndour", types: ["dark", "fire"], gen: 2, evolutions: 2 },
    { id: 229, name: "Houndoom", types: ["dark", "fire"], gen: 2, evolutions: 2 },
    { id: 230, name: "Kingdra", types: ["water", "dragon"], gen: 2, evolutions: 3 },
    { id: 231, name: "Phanpy", types: ["ground"], gen: 2, evolutions: 2 },
    { id: 232, name: "Donphan", types: ["ground"], gen: 2, evolutions: 2 },
    { id: 233, name: "Porygon2", types: ["normal"], gen: 2, evolutions: 3 },
    { id: 234, name: "Stantler", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 235, name: "Smeargle", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 236, name: "Tyrogue", types: ["fighting"], gen: 2, evolutions: 2 },
    { id: 237, name: "Hitmontop", types: ["fighting"], gen: 2, evolutions: 2 },
    { id: 238, name: "Smoochum", types: ["ice", "psychic"], gen: 2, evolutions: 2 },
    { id: 239, name: "Elekid", types: ["electric"], gen: 2, evolutions: 3 },
    { id: 240, name: "Magby", types: ["fire"], gen: 2, evolutions: 3 },
    { id: 241, name: "Miltank", types: ["normal"], gen: 2, evolutions: 1 },
    { id: 242, name: "Blissey", types: ["normal"], gen: 2, evolutions: 3 },
    { id: 243, name: "Raikou", types: ["electric"], gen: 2, evolutions: 1 },
    { id: 244, name: "Entei", types: ["fire"], gen: 2, evolutions: 1 },
    { id: 245, name: "Suicune", types: ["water"], gen: 2, evolutions: 1 },
    { id: 246, name: "Larvitar", types: ["rock", "ground"], gen: 2, evolutions: 3 },
    { id: 247, name: "Pupitar", types: ["rock", "ground"], gen: 2, evolutions: 3 },
    { id: 248, name: "Tyranitar", types: ["rock", "dark"], gen: 2, evolutions: 3 },
    { id: 249, name: "Lugia", types: ["psychic", "flying"], gen: 2, evolutions: 1 },
    { id: 250, name: "Ho-Oh", types: ["fire", "flying"], gen: 2, evolutions: 1 },
    { id: 251, name: "Celebi", types: ["psychic", "grass"], gen: 2, evolutions: 1 },
    // === Generation 3 (Hoenn) ===
    { id: 252, name: "Treecko", types: ["grass"], gen: 3, evolutions: 3 },
    { id: 253, name: "Grovyle", types: ["grass"], gen: 3, evolutions: 3 },
    { id: 254, name: "Sceptile", types: ["grass"], gen: 3, evolutions: 3 },
    { id: 255, name: "Torchic", types: ["fire"], gen: 3, evolutions: 3 },
    { id: 256, name: "Combusken", types: ["fire", "fighting"], gen: 3, evolutions: 3 },
    { id: 257, name: "Blaziken", types: ["fire", "fighting"], gen: 3, evolutions: 3 },
    { id: 258, name: "Mudkip", types: ["water"], gen: 3, evolutions: 3 },
    { id: 259, name: "Marshtomp", types: ["water", "ground"], gen: 3, evolutions: 3 },
    { id: 260, name: "Swampert", types: ["water", "ground"], gen: 3, evolutions: 3 },
    { id: 261, name: "Poochyena", types: ["dark"], gen: 3, evolutions: 2 },
    { id: 262, name: "Mightyena", types: ["dark"], gen: 3, evolutions: 2 },
    { id: 263, name: "Zigzagoon", types: ["normal"], gen: 3, evolutions: 2 },
    { id: 264, name: "Linoone", types: ["normal"], gen: 3, evolutions: 2 },
    { id: 265, name: "Wurmple", types: ["bug"], gen: 3, evolutions: 2 },
    { id: 266, name: "Silcoon", types: ["bug"], gen: 3, evolutions: 2 },
    { id: 267, name: "Beautifly", types: ["bug", "flying"], gen: 3, evolutions: 2 },
    { id: 268, name: "Cascoon", types: ["bug"], gen: 3, evolutions: 2 },
    { id: 269, name: "Dustox", types: ["bug", "poison"], gen: 3, evolutions: 2 },
    { id: 270, name: "Lotad", types: ["water", "grass"], gen: 3, evolutions: 3 },
    { id: 271, name: "Lombre", types: ["water", "grass"], gen: 3, evolutions: 3 },
    { id: 272, name: "Ludicolo", types: ["water", "grass"], gen: 3, evolutions: 3 },
    { id: 273, name: "Seedot", types: ["grass"], gen: 3, evolutions: 3 },
    { id: 274, name: "Nuzleaf", types: ["grass", "dark"], gen: 3, evolutions: 3 },
    { id: 275, name: "Shiftry", types: ["grass", "dark"], gen: 3, evolutions: 3 },
    { id: 276, name: "Taillow", types: ["normal", "flying"], gen: 3, evolutions: 2 },
    { id: 277, name: "Swellow", types: ["normal", "flying"], gen: 3, evolutions: 2 },
    { id: 278, name: "Wingull", types: ["water", "flying"], gen: 3, evolutions: 2 },
    { id: 279, name: "Pelipper", types: ["water", "flying"], gen: 3, evolutions: 2 },
    { id: 280, name: "Ralts", types: ["psychic", "fairy"], gen: 3, evolutions: 3 },
    { id: 281, name: "Kirlia", types: ["psychic", "fairy"], gen: 3, evolutions: 3 },
    { id: 282, name: "Gardevoir", types: ["psychic", "fairy"], gen: 3, evolutions: 3 },
    { id: 283, name: "Surskit", types: ["bug", "water"], gen: 3, evolutions: 2 },
    { id: 284, name: "Masquerain", types: ["bug", "flying"], gen: 3, evolutions: 2 },
    { id: 285, name: "Shroomish", types: ["grass"], gen: 3, evolutions: 2 },
    { id: 286, name: "Breloom", types: ["grass", "fighting"], gen: 3, evolutions: 2 },
    { id: 287, name: "Slakoth", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 288, name: "Vigoroth", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 289, name: "Slaking", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 290, name: "Nincada", types: ["bug", "ground"], gen: 3, evolutions: 2 },
    { id: 291, name: "Ninjask", types: ["bug", "flying"], gen: 3, evolutions: 2 },
    { id: 292, name: "Shedinja", types: ["bug", "ghost"], gen: 3, evolutions: 1 },
    { id: 293, name: "Whismur", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 294, name: "Loudred", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 295, name: "Exploud", types: ["normal"], gen: 3, evolutions: 3 },
    { id: 296, name: "Makuhita", types: ["fighting"], gen: 3, evolutions: 2 },
    { id: 297, name: "Hariyama", types: ["fighting"], gen: 3, evolutions: 2 },
    { id: 298, name: "Azurill", types: ["normal", "fairy"], gen: 3, evolutions: 3 },
    { id: 299, name: "Nosepass", types: ["rock"], gen: 3, evolutions: 2 },
    { id: 300, name: "Skitty", types: ["normal"], gen: 3, evolutions: 2 },
    { id: 301, name: "Delcatty", types: ["normal"], gen: 3, evolutions: 2 },
    { id: 302, name: "Sableye", types: ["dark", "ghost"], gen: 3, evolutions: 1 },
    { id: 303, name: "Mawile", types: ["steel", "fairy"], gen: 3, evolutions: 1 },
    { id: 304, name: "Aron", types: ["steel", "rock"], gen: 3, evolutions: 3 },
    { id: 305, name: "Lairon", types: ["steel", "rock"], gen: 3, evolutions: 3 },
    { id: 306, name: "Aggron", types: ["steel", "rock"], gen: 3, evolutions: 3 },
    { id: 307, name: "Meditite", types: ["fighting", "psychic"], gen: 3, evolutions: 2 },
    { id: 308, name: "Medicham", types: ["fighting", "psychic"], gen: 3, evolutions: 2 },
    { id: 309, name: "Electrike", types: ["electric"], gen: 3, evolutions: 2 },
    { id: 310, name: "Manectric", types: ["electric"], gen: 3, evolutions: 2 },
    { id: 311, name: "Plusle", types: ["electric"], gen: 3, evolutions: 1 },
    { id: 312, name: "Minun", types: ["electric"], gen: 3, evolutions: 1 },
    { id: 313, name: "Volbeat", types: ["bug"], gen: 3, evolutions: 1 },
    { id: 314, name: "Illumise", types: ["bug"], gen: 3, evolutions: 1 },
    { id: 315, name: "Roselia", types: ["grass", "poison"], gen: 3, evolutions: 3 },
    { id: 316, name: "Gulpin", types: ["poison"], gen: 3, evolutions: 2 },
    { id: 317, name: "Swalot", types: ["poison"], gen: 3, evolutions: 2 },
    { id: 318, name: "Carvanha", types: ["water", "dark"], gen: 3, evolutions: 2 },
    { id: 319, name: "Sharpedo", types: ["water", "dark"], gen: 3, evolutions: 2 },
    { id: 320, name: "Wailmer", types: ["water"], gen: 3, evolutions: 2 },
    { id: 321, name: "Wailord", types: ["water"], gen: 3, evolutions: 2 },
    { id: 322, name: "Numel", types: ["fire", "ground"], gen: 3, evolutions: 2 },
    { id: 323, name: "Camerupt", types: ["fire", "ground"], gen: 3, evolutions: 2 },
    { id: 324, name: "Torkoal", types: ["fire"], gen: 3, evolutions: 1 },
    { id: 325, name: "Spoink", types: ["psychic"], gen: 3, evolutions: 2 },
    { id: 326, name: "Grumpig", types: ["psychic"], gen: 3, evolutions: 2 },
    { id: 327, name: "Spinda", types: ["normal"], gen: 3, evolutions: 1 },
    { id: 328, name: "Trapinch", types: ["ground"], gen: 3, evolutions: 3 },
    { id: 329, name: "Vibrava", types: ["ground", "dragon"], gen: 3, evolutions: 3 },
    { id: 330, name: "Flygon", types: ["ground", "dragon"], gen: 3, evolutions: 3 },
    { id: 331, name: "Cacnea", types: ["grass"], gen: 3, evolutions: 2 },
    { id: 332, name: "Cacturne", types: ["grass", "dark"], gen: 3, evolutions: 2 },
    { id: 333, name: "Swablu", types: ["normal", "flying"], gen: 3, evolutions: 2 },
    { id: 334, name: "Altaria", types: ["dragon", "flying"], gen: 3, evolutions: 2 },
    { id: 335, name: "Zangoose", types: ["normal"], gen: 3, evolutions: 1 },
    { id: 336, name: "Seviper", types: ["poison"], gen: 3, evolutions: 1 },
    { id: 337, name: "Lunatone", types: ["rock", "psychic"], gen: 3, evolutions: 1 },
    { id: 338, name: "Solrock", types: ["rock", "psychic"], gen: 3, evolutions: 1 },
    { id: 339, name: "Barboach", types: ["water", "ground"], gen: 3, evolutions: 2 },
    { id: 340, name: "Whiscash", types: ["water", "ground"], gen: 3, evolutions: 2 },
    { id: 341, name: "Corphish", types: ["water"], gen: 3, evolutions: 2 },
    { id: 342, name: "Crawdaunt", types: ["water", "dark"], gen: 3, evolutions: 2 },
    { id: 343, name: "Baltoy", types: ["ground", "psychic"], gen: 3, evolutions: 2 },
    { id: 344, name: "Claydol", types: ["ground", "psychic"], gen: 3, evolutions: 2 },
    { id: 345, name: "Lileep", types: ["rock", "grass"], gen: 3, evolutions: 2 },
    { id: 346, name: "Cradily", types: ["rock", "grass"], gen: 3, evolutions: 2 },
    { id: 347, name: "Anorith", types: ["rock", "bug"], gen: 3, evolutions: 2 },
    { id: 348, name: "Armaldo", types: ["rock", "bug"], gen: 3, evolutions: 2 },
    { id: 349, name: "Feebas", types: ["water"], gen: 3, evolutions: 2 },
    { id: 350, name: "Milotic", types: ["water"], gen: 3, evolutions: 2 },
    { id: 351, name: "Castform", types: ["normal"], gen: 3, evolutions: 1 },
    { id: 352, name: "Kecleon", types: ["normal"], gen: 3, evolutions: 1 },
    { id: 353, name: "Shuppet", types: ["ghost"], gen: 3, evolutions: 2 },
    { id: 354, name: "Banette", types: ["ghost"], gen: 3, evolutions: 2 },
    { id: 355, name: "Duskull", types: ["ghost"], gen: 3, evolutions: 3 },
    { id: 356, name: "Dusclops", types: ["ghost"], gen: 3, evolutions: 3 },
    { id: 357, name: "Tropius", types: ["grass", "flying"], gen: 3, evolutions: 1 },
    { id: 358, name: "Chimecho", types: ["psychic"], gen: 3, evolutions: 2 },
    { id: 359, name: "Absol", types: ["dark"], gen: 3, evolutions: 1 },
    { id: 360, name: "Wynaut", types: ["psychic"], gen: 3, evolutions: 2 },
    { id: 361, name: "Snorunt", types: ["ice"], gen: 3, evolutions: 2 },
    { id: 362, name: "Glalie", types: ["ice"], gen: 3, evolutions: 2 },
    { id: 363, name: "Spheal", types: ["ice", "water"], gen: 3, evolutions: 3 },
    { id: 364, name: "Sealeo", types: ["ice", "water"], gen: 3, evolutions: 3 },
    { id: 365, name: "Walrein", types: ["ice", "water"], gen: 3, evolutions: 3 },
    { id: 366, name: "Clamperl", types: ["water"], gen: 3, evolutions: 2 },
    { id: 367, name: "Huntail", types: ["water"], gen: 3, evolutions: 2 },
    { id: 368, name: "Gorebyss", types: ["water"], gen: 3, evolutions: 2 },
    { id: 369, name: "Relicanth", types: ["water", "rock"], gen: 3, evolutions: 1 },
    { id: 370, name: "Luvdisc", types: ["water"], gen: 3, evolutions: 1 },
    { id: 371, name: "Bagon", types: ["dragon"], gen: 3, evolutions: 3 },
    { id: 372, name: "Shelgon", types: ["dragon"], gen: 3, evolutions: 3 },
    { id: 373, name: "Salamence", types: ["dragon", "flying"], gen: 3, evolutions: 3 },
    { id: 374, name: "Beldum", types: ["steel", "psychic"], gen: 3, evolutions: 3 },
    { id: 375, name: "Metang", types: ["steel", "psychic"], gen: 3, evolutions: 3 },
    { id: 376, name: "Metagross", types: ["steel", "psychic"], gen: 3, evolutions: 3 },
    { id: 377, name: "Regirock", types: ["rock"], gen: 3, evolutions: 1 },
    { id: 378, name: "Regice", types: ["ice"], gen: 3, evolutions: 1 },
    { id: 379, name: "Registeel", types: ["steel"], gen: 3, evolutions: 1 },
    { id: 380, name: "Latias", types: ["dragon", "psychic"], gen: 3, evolutions: 1 },
    { id: 381, name: "Latios", types: ["dragon", "psychic"], gen: 3, evolutions: 1 },
    { id: 382, name: "Kyogre", types: ["water"], gen: 3, evolutions: 1 },
    { id: 383, name: "Groudon", types: ["ground"], gen: 3, evolutions: 1 },
    { id: 384, name: "Rayquaza", types: ["dragon", "flying"], gen: 3, evolutions: 1 },
    { id: 385, name: "Jirachi", types: ["steel", "psychic"], gen: 3, evolutions: 1 },
    { id: 386, name: "Deoxys", types: ["psychic"], gen: 3, evolutions: 1 },
    // === Generation 4 (Sinnoh) ===
    { id: 387, name: "Turtwig", types: ["grass"], gen: 4, evolutions: 3 },
    { id: 388, name: "Grotle", types: ["grass"], gen: 4, evolutions: 3 },
    { id: 389, name: "Torterra", types: ["grass", "ground"], gen: 4, evolutions: 3 },
    { id: 390, name: "Chimchar", types: ["fire"], gen: 4, evolutions: 3 },
    { id: 391, name: "Monferno", types: ["fire", "fighting"], gen: 4, evolutions: 3 },
    { id: 392, name: "Infernape", types: ["fire", "fighting"], gen: 4, evolutions: 3 },
    { id: 393, name: "Piplup", types: ["water"], gen: 4, evolutions: 3 },
    { id: 394, name: "Prinplup", types: ["water"], gen: 4, evolutions: 3 },
    { id: 395, name: "Empoleon", types: ["water", "steel"], gen: 4, evolutions: 3 },
    { id: 396, name: "Starly", types: ["normal", "flying"], gen: 4, evolutions: 3 },
    { id: 397, name: "Staravia", types: ["normal", "flying"], gen: 4, evolutions: 3 },
    { id: 398, name: "Staraptor", types: ["normal", "flying"], gen: 4, evolutions: 3 },
    { id: 399, name: "Bidoof", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 400, name: "Bibarel", types: ["normal", "water"], gen: 4, evolutions: 2 },
    { id: 401, name: "Kricketot", types: ["bug"], gen: 4, evolutions: 2 },
    { id: 402, name: "Kricketune", types: ["bug"], gen: 4, evolutions: 2 },
    { id: 403, name: "Shinx", types: ["electric"], gen: 4, evolutions: 3 },
    { id: 404, name: "Luxio", types: ["electric"], gen: 4, evolutions: 3 },
    { id: 405, name: "Luxray", types: ["electric"], gen: 4, evolutions: 3 },
    { id: 406, name: "Budew", types: ["grass", "poison"], gen: 4, evolutions: 3 },
    { id: 407, name: "Roserade", types: ["grass", "poison"], gen: 4, evolutions: 3 },
    { id: 408, name: "Cranidos", types: ["rock"], gen: 4, evolutions: 2 },
    { id: 409, name: "Rampardos", types: ["rock"], gen: 4, evolutions: 2 },
    { id: 410, name: "Shieldon", types: ["rock", "steel"], gen: 4, evolutions: 2 },
    { id: 411, name: "Bastiodon", types: ["rock", "steel"], gen: 4, evolutions: 2 },
    { id: 412, name: "Burmy", types: ["bug"], gen: 4, evolutions: 2 },
    { id: 413, name: "Wormadam", types: ["bug", "grass"], gen: 4, evolutions: 2 },
    { id: 414, name: "Mothim", types: ["bug", "flying"], gen: 4, evolutions: 2 },
    { id: 415, name: "Combee", types: ["bug", "flying"], gen: 4, evolutions: 2 },
    { id: 416, name: "Vespiquen", types: ["bug", "flying"], gen: 4, evolutions: 2 },
    { id: 417, name: "Pachirisu", types: ["electric"], gen: 4, evolutions: 1 },
    { id: 418, name: "Buizel", types: ["water"], gen: 4, evolutions: 2 },
    { id: 419, name: "Floatzel", types: ["water"], gen: 4, evolutions: 2 },
    { id: 420, name: "Cherubi", types: ["grass"], gen: 4, evolutions: 2 },
    { id: 421, name: "Cherrim", types: ["grass"], gen: 4, evolutions: 2 },
    { id: 422, name: "Shellos", types: ["water"], gen: 4, evolutions: 2 },
    { id: 423, name: "Gastrodon", types: ["water", "ground"], gen: 4, evolutions: 2 },
    { id: 424, name: "Ambipom", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 425, name: "Drifloon", types: ["ghost", "flying"], gen: 4, evolutions: 2 },
    { id: 426, name: "Drifblim", types: ["ghost", "flying"], gen: 4, evolutions: 2 },
    { id: 427, name: "Buneary", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 428, name: "Lopunny", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 429, name: "Mismagius", types: ["ghost"], gen: 4, evolutions: 2 },
    { id: 430, name: "Honchkrow", types: ["dark", "flying"], gen: 4, evolutions: 2 },
    { id: 431, name: "Glameow", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 432, name: "Purugly", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 433, name: "Chingling", types: ["psychic"], gen: 4, evolutions: 2 },
    { id: 434, name: "Stunky", types: ["poison", "dark"], gen: 4, evolutions: 2 },
    { id: 435, name: "Skuntank", types: ["poison", "dark"], gen: 4, evolutions: 2 },
    { id: 436, name: "Bronzor", types: ["steel", "psychic"], gen: 4, evolutions: 2 },
    { id: 437, name: "Bronzong", types: ["steel", "psychic"], gen: 4, evolutions: 2 },
    { id: 438, name: "Bonsly", types: ["rock"], gen: 4, evolutions: 2 },
    { id: 439, name: "Mime Jr.", types: ["psychic", "fairy"], gen: 4, evolutions: 2 },
    { id: 440, name: "Happiny", types: ["normal"], gen: 4, evolutions: 3 },
    { id: 441, name: "Chatot", types: ["normal", "flying"], gen: 4, evolutions: 1 },
    { id: 442, name: "Spiritomb", types: ["ghost", "dark"], gen: 4, evolutions: 1 },
    { id: 443, name: "Gible", types: ["dragon", "ground"], gen: 4, evolutions: 3 },
    { id: 444, name: "Gabite", types: ["dragon", "ground"], gen: 4, evolutions: 3 },
    { id: 445, name: "Garchomp", types: ["dragon", "ground"], gen: 4, evolutions: 3 },
    { id: 446, name: "Munchlax", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 447, name: "Riolu", types: ["fighting"], gen: 4, evolutions: 2 },
    { id: 448, name: "Lucario", types: ["fighting", "steel"], gen: 4, evolutions: 2 },
    { id: 449, name: "Hippopotas", types: ["ground"], gen: 4, evolutions: 2 },
    { id: 450, name: "Hippowdon", types: ["ground"], gen: 4, evolutions: 2 },
    { id: 451, name: "Skorupi", types: ["poison", "bug"], gen: 4, evolutions: 2 },
    { id: 452, name: "Drapion", types: ["poison", "dark"], gen: 4, evolutions: 2 },
    { id: 453, name: "Croagunk", types: ["poison", "fighting"], gen: 4, evolutions: 2 },
    { id: 454, name: "Toxicroak", types: ["poison", "fighting"], gen: 4, evolutions: 2 },
    { id: 455, name: "Carnivine", types: ["grass"], gen: 4, evolutions: 1 },
    { id: 456, name: "Finneon", types: ["water"], gen: 4, evolutions: 2 },
    { id: 457, name: "Lumineon", types: ["water"], gen: 4, evolutions: 2 },
    { id: 458, name: "Mantyke", types: ["water", "flying"], gen: 4, evolutions: 2 },
    { id: 459, name: "Snover", types: ["grass", "ice"], gen: 4, evolutions: 2 },
    { id: 460, name: "Abomasnow", types: ["grass", "ice"], gen: 4, evolutions: 2 },
    { id: 461, name: "Weavile", types: ["dark", "ice"], gen: 4, evolutions: 2 },
    { id: 462, name: "Magnezone", types: ["electric", "steel"], gen: 4, evolutions: 3 },
    { id: 463, name: "Lickilicky", types: ["normal"], gen: 4, evolutions: 2 },
    { id: 464, name: "Rhyperior", types: ["ground", "rock"], gen: 4, evolutions: 3 },
    { id: 465, name: "Tangrowth", types: ["grass"], gen: 4, evolutions: 2 },
    { id: 466, name: "Electivire", types: ["electric"], gen: 4, evolutions: 3 },
    { id: 467, name: "Magmortar", types: ["fire"], gen: 4, evolutions: 3 },
    { id: 468, name: "Togekiss", types: ["fairy", "flying"], gen: 4, evolutions: 3 },
    { id: 469, name: "Yanmega", types: ["bug", "flying"], gen: 4, evolutions: 2 },
    { id: 470, name: "Leafeon", types: ["grass"], gen: 4, evolutions: 2 },
    { id: 471, name: "Glaceon", types: ["ice"], gen: 4, evolutions: 2 },
    { id: 472, name: "Gliscor", types: ["ground", "flying"], gen: 4, evolutions: 2 },
    { id: 473, name: "Mamoswine", types: ["ice", "ground"], gen: 4, evolutions: 3 },
    { id: 474, name: "Porygon-Z", types: ["normal"], gen: 4, evolutions: 3 },
    { id: 475, name: "Gallade", types: ["psychic", "fighting"], gen: 4, evolutions: 3 },
    { id: 476, name: "Probopass", types: ["rock", "steel"], gen: 4, evolutions: 2 },
    { id: 477, name: "Dusknoir", types: ["ghost"], gen: 4, evolutions: 3 },
    { id: 478, name: "Froslass", types: ["ice", "ghost"], gen: 4, evolutions: 2 },
    { id: 479, name: "Rotom", types: ["electric", "ghost"], gen: 4, evolutions: 1 },
    { id: 480, name: "Uxie", types: ["psychic"], gen: 4, evolutions: 1 },
    { id: 481, name: "Mesprit", types: ["psychic"], gen: 4, evolutions: 1 },
    { id: 482, name: "Azelf", types: ["psychic"], gen: 4, evolutions: 1 },
    { id: 483, name: "Dialga", types: ["steel", "dragon"], gen: 4, evolutions: 1 },
    { id: 484, name: "Palkia", types: ["water", "dragon"], gen: 4, evolutions: 1 },
    { id: 485, name: "Heatran", types: ["fire", "steel"], gen: 4, evolutions: 1 },
    { id: 486, name: "Regigigas", types: ["normal"], gen: 4, evolutions: 1 },
    { id: 487, name: "Giratina", types: ["ghost", "dragon"], gen: 4, evolutions: 1 },
    { id: 488, name: "Cresselia", types: ["psychic"], gen: 4, evolutions: 1 },
    { id: 489, name: "Phione", types: ["water"], gen: 4, evolutions: 1 },
    { id: 490, name: "Manaphy", types: ["water"], gen: 4, evolutions: 1 },
    { id: 491, name: "Darkrai", types: ["dark"], gen: 4, evolutions: 1 },
    { id: 492, name: "Shaymin", types: ["grass"], gen: 4, evolutions: 1 },
    { id: 493, name: "Arceus", types: ["normal"], gen: 4, evolutions: 1 },
    // === Generation 5 (Unova) ===
    { id: 494, name: "Victini", types: ["psychic", "fire"], gen: 5, evolutions: 1 },
    { id: 495, name: "Snivy", types: ["grass"], gen: 5, evolutions: 3 },
    { id: 496, name: "Servine", types: ["grass"], gen: 5, evolutions: 3 },
    { id: 497, name: "Serperior", types: ["grass"], gen: 5, evolutions: 3 },
    { id: 498, name: "Tepig", types: ["fire"], gen: 5, evolutions: 3 },
    { id: 499, name: "Pignite", types: ["fire", "fighting"], gen: 5, evolutions: 3 },
    { id: 500, name: "Emboar", types: ["fire", "fighting"], gen: 5, evolutions: 3 },
    { id: 501, name: "Oshawott", types: ["water"], gen: 5, evolutions: 3 },
    { id: 502, name: "Dewott", types: ["water"], gen: 5, evolutions: 3 },
    { id: 503, name: "Samurott", types: ["water"], gen: 5, evolutions: 3 },
    { id: 504, name: "Patrat", types: ["normal"], gen: 5, evolutions: 2 },
    { id: 505, name: "Watchog", types: ["normal"], gen: 5, evolutions: 2 },
    { id: 506, name: "Lillipup", types: ["normal"], gen: 5, evolutions: 3 },
    { id: 507, name: "Herdier", types: ["normal"], gen: 5, evolutions: 3 },
    { id: 508, name: "Stoutland", types: ["normal"], gen: 5, evolutions: 3 },
    { id: 509, name: "Purrloin", types: ["dark"], gen: 5, evolutions: 2 },
    { id: 510, name: "Liepard", types: ["dark"], gen: 5, evolutions: 2 },
    { id: 511, name: "Pansage", types: ["grass"], gen: 5, evolutions: 2 },
    { id: 512, name: "Simisage", types: ["grass"], gen: 5, evolutions: 2 },
    { id: 513, name: "Pansear", types: ["fire"], gen: 5, evolutions: 2 },
    { id: 514, name: "Simisear", types: ["fire"], gen: 5, evolutions: 2 },
    { id: 515, name: "Panpour", types: ["water"], gen: 5, evolutions: 2 },
    { id: 516, name: "Simipour", types: ["water"], gen: 5, evolutions: 2 },
    { id: 517, name: "Munna", types: ["psychic"], gen: 5, evolutions: 2 },
    { id: 518, name: "Musharna", types: ["psychic"], gen: 5, evolutions: 2 },
    { id: 519, name: "Pidove", types: ["normal", "flying"], gen: 5, evolutions: 3 },
    { id: 520, name: "Tranquill", types: ["normal", "flying"], gen: 5, evolutions: 3 },
    { id: 521, name: "Unfezant", types: ["normal", "flying"], gen: 5, evolutions: 3 },
    { id: 522, name: "Blitzle", types: ["electric"], gen: 5, evolutions: 2 },
    { id: 523, name: "Zebstrika", types: ["electric"], gen: 5, evolutions: 2 },
    { id: 524, name: "Roggenrola", types: ["rock"], gen: 5, evolutions: 3 },
    { id: 525, name: "Boldore", types: ["rock"], gen: 5, evolutions: 3 },
    { id: 526, name: "Gigalith", types: ["rock"], gen: 5, evolutions: 3 },
    { id: 527, name: "Woobat", types: ["psychic", "flying"], gen: 5, evolutions: 2 },
    { id: 528, name: "Swoobat", types: ["psychic", "flying"], gen: 5, evolutions: 2 },
    { id: 529, name: "Drilbur", types: ["ground"], gen: 5, evolutions: 2 },
    { id: 530, name: "Excadrill", types: ["ground", "steel"], gen: 5, evolutions: 2 },
    { id: 531, name: "Audino", types: ["normal"], gen: 5, evolutions: 1 },
    { id: 532, name: "Timburr", types: ["fighting"], gen: 5, evolutions: 3 },
    { id: 533, name: "Gurdurr", types: ["fighting"], gen: 5, evolutions: 3 },
    { id: 534, name: "Conkeldurr", types: ["fighting"], gen: 5, evolutions: 3 },
    { id: 535, name: "Tympole", types: ["water"], gen: 5, evolutions: 3 },
    { id: 536, name: "Palpitoad", types: ["water", "ground"], gen: 5, evolutions: 3 },
    { id: 537, name: "Seismitoad", types: ["water", "ground"], gen: 5, evolutions: 3 },
    { id: 538, name: "Throh", types: ["fighting"], gen: 5, evolutions: 1 },
    { id: 539, name: "Sawk", types: ["fighting"], gen: 5, evolutions: 1 },
    { id: 540, name: "Sewaddle", types: ["bug", "grass"], gen: 5, evolutions: 3 },
    { id: 541, name: "Swadloon", types: ["bug", "grass"], gen: 5, evolutions: 3 },
    { id: 542, name: "Leavanny", types: ["bug", "grass"], gen: 5, evolutions: 3 },
    { id: 543, name: "Venipede", types: ["bug", "poison"], gen: 5, evolutions: 3 },
    { id: 544, name: "Whirlipede", types: ["bug", "poison"], gen: 5, evolutions: 3 },
    { id: 545, name: "Scolipede", types: ["bug", "poison"], gen: 5, evolutions: 3 },
    { id: 546, name: "Cottonee", types: ["grass", "fairy"], gen: 5, evolutions: 2 },
    { id: 547, name: "Whimsicott", types: ["grass", "fairy"], gen: 5, evolutions: 2 },
    { id: 548, name: "Petilil", types: ["grass"], gen: 5, evolutions: 2 },
    { id: 549, name: "Lilligant", types: ["grass"], gen: 5, evolutions: 2 },
    { id: 550, name: "Basculin", types: ["water"], gen: 5, evolutions: 1 },
    { id: 551, name: "Sandile", types: ["ground", "dark"], gen: 5, evolutions: 3 },
    { id: 552, name: "Krokorok", types: ["ground", "dark"], gen: 5, evolutions: 3 },
    { id: 553, name: "Krookodile", types: ["ground", "dark"], gen: 5, evolutions: 3 },
    { id: 554, name: "Darumaka", types: ["fire"], gen: 5, evolutions: 2 },
    { id: 555, name: "Darmanitan", types: ["fire"], gen: 5, evolutions: 2 },
    { id: 556, name: "Maractus", types: ["grass"], gen: 5, evolutions: 1 },
    { id: 557, name: "Dwebble", types: ["bug", "rock"], gen: 5, evolutions: 2 },
    { id: 558, name: "Crustle", types: ["bug", "rock"], gen: 5, evolutions: 2 },
    { id: 559, name: "Scraggy", types: ["dark", "fighting"], gen: 5, evolutions: 2 },
    { id: 560, name: "Scrafty", types: ["dark", "fighting"], gen: 5, evolutions: 2 },
    { id: 561, name: "Sigilyph", types: ["psychic", "flying"], gen: 5, evolutions: 1 },
    { id: 562, name: "Yamask", types: ["ghost"], gen: 5, evolutions: 2 },
    { id: 563, name: "Cofagrigus", types: ["ghost"], gen: 5, evolutions: 2 },
    { id: 564, name: "Tirtouga", types: ["water", "rock"], gen: 5, evolutions: 2 },
    { id: 565, name: "Carracosta", types: ["water", "rock"], gen: 5, evolutions: 2 },
    { id: 566, name: "Archen", types: ["rock", "flying"], gen: 5, evolutions: 2 },
    { id: 567, name: "Archeops", types: ["rock", "flying"], gen: 5, evolutions: 2 },
    { id: 568, name: "Trubbish", types: ["poison"], gen: 5, evolutions: 2 },
    { id: 569, name: "Garbodor", types: ["poison"], gen: 5, evolutions: 2 },
    { id: 570, name: "Zorua", types: ["dark"], gen: 5, evolutions: 2 },
    { id: 571, name: "Zoroark", types: ["dark"], gen: 5, evolutions: 2 },
    { id: 572, name: "Minccino", types: ["normal"], gen: 5, evolutions: 2 },
    { id: 573, name: "Cinccino", types: ["normal"], gen: 5, evolutions: 2 },
    { id: 574, name: "Gothita", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 575, name: "Gothorita", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 576, name: "Gothitelle", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 577, name: "Solosis", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 578, name: "Duosion", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 579, name: "Reuniclus", types: ["psychic"], gen: 5, evolutions: 3 },
    { id: 580, name: "Ducklett", types: ["water", "flying"], gen: 5, evolutions: 2 },
    { id: 581, name: "Swanna", types: ["water", "flying"], gen: 5, evolutions: 2 },
    { id: 582, name: "Vanillite", types: ["ice"], gen: 5, evolutions: 3 },
    { id: 583, name: "Vanillish", types: ["ice"], gen: 5, evolutions: 3 },
    { id: 584, name: "Vanilluxe", types: ["ice"], gen: 5, evolutions: 3 },
    { id: 585, name: "Deerling", types: ["normal", "grass"], gen: 5, evolutions: 2 },
    { id: 586, name: "Sawsbuck", types: ["normal", "grass"], gen: 5, evolutions: 2 },
    { id: 587, name: "Emolga", types: ["electric", "flying"], gen: 5, evolutions: 1 },
    { id: 588, name: "Karrablast", types: ["bug"], gen: 5, evolutions: 2 },
    { id: 589, name: "Escavalier", types: ["bug", "steel"], gen: 5, evolutions: 2 },
    { id: 590, name: "Foongus", types: ["grass", "poison"], gen: 5, evolutions: 2 },
    { id: 591, name: "Amoonguss", types: ["grass", "poison"], gen: 5, evolutions: 2 },
    { id: 592, name: "Frillish", types: ["water", "ghost"], gen: 5, evolutions: 2 },
    { id: 593, name: "Jellicent", types: ["water", "ghost"], gen: 5, evolutions: 2 },
    { id: 594, name: "Alomomola", types: ["water"], gen: 5, evolutions: 1 },
    { id: 595, name: "Joltik", types: ["bug", "electric"], gen: 5, evolutions: 2 },
    { id: 596, name: "Galvantula", types: ["bug", "electric"], gen: 5, evolutions: 2 },
    { id: 597, name: "Ferroseed", types: ["grass", "steel"], gen: 5, evolutions: 2 },
    { id: 598, name: "Ferrothorn", types: ["grass", "steel"], gen: 5, evolutions: 2 },
    { id: 599, name: "Klink", types: ["steel"], gen: 5, evolutions: 3 },
    { id: 600, name: "Klang", types: ["steel"], gen: 5, evolutions: 3 },
    { id: 601, name: "Klinklang", types: ["steel"], gen: 5, evolutions: 3 },
    { id: 602, name: "Tynamo", types: ["electric"], gen: 5, evolutions: 3 },
    { id: 603, name: "Eelektrik", types: ["electric"], gen: 5, evolutions: 3 },
    { id: 604, name: "Eelektross", types: ["electric"], gen: 5, evolutions: 3 },
    { id: 605, name: "Elgyem", types: ["psychic"], gen: 5, evolutions: 2 },
    { id: 606, name: "Beheeyem", types: ["psychic"], gen: 5, evolutions: 2 },
    { id: 607, name: "Litwick", types: ["ghost", "fire"], gen: 5, evolutions: 3 },
    { id: 608, name: "Lampent", types: ["ghost", "fire"], gen: 5, evolutions: 3 },
    { id: 609, name: "Chandelure", types: ["ghost", "fire"], gen: 5, evolutions: 3 },
    { id: 610, name: "Axew", types: ["dragon"], gen: 5, evolutions: 3 },
    { id: 611, name: "Fraxure", types: ["dragon"], gen: 5, evolutions: 3 },
    { id: 612, name: "Haxorus", types: ["dragon"], gen: 5, evolutions: 3 },
    { id: 613, name: "Cubchoo", types: ["ice"], gen: 5, evolutions: 2 },
    { id: 614, name: "Beartic", types: ["ice"], gen: 5, evolutions: 2 },
    { id: 615, name: "Cryogonal", types: ["ice"], gen: 5, evolutions: 1 },
    { id: 616, name: "Shelmet", types: ["bug"], gen: 5, evolutions: 2 },
    { id: 617, name: "Accelgor", types: ["bug"], gen: 5, evolutions: 2 },
    { id: 618, name: "Stunfisk", types: ["ground", "electric"], gen: 5, evolutions: 1 },
    { id: 619, name: "Mienfoo", types: ["fighting"], gen: 5, evolutions: 2 },
    { id: 620, name: "Mienshao", types: ["fighting"], gen: 5, evolutions: 2 },
    { id: 621, name: "Druddigon", types: ["dragon"], gen: 5, evolutions: 1 },
    { id: 622, name: "Golett", types: ["ghost", "ground"], gen: 5, evolutions: 2 },
    { id: 623, name: "Golurk", types: ["ghost", "ground"], gen: 5, evolutions: 2 },
    { id: 624, name: "Pawniard", types: ["dark", "steel"], gen: 5, evolutions: 2 },
    { id: 625, name: "Bisharp", types: ["dark", "steel"], gen: 5, evolutions: 2 },
    { id: 626, name: "Bouffalant", types: ["normal"], gen: 5, evolutions: 1 },
    { id: 627, name: "Rufflet", types: ["normal", "flying"], gen: 5, evolutions: 2 },
    { id: 628, name: "Braviary", types: ["normal", "flying"], gen: 5, evolutions: 2 },
    { id: 629, name: "Vullaby", types: ["dark", "flying"], gen: 5, evolutions: 2 },
    { id: 630, name: "Mandibuzz", types: ["dark", "flying"], gen: 5, evolutions: 2 },
    { id: 631, name: "Heatmor", types: ["fire"], gen: 5, evolutions: 1 },
    { id: 632, name: "Durant", types: ["bug", "steel"], gen: 5, evolutions: 1 },
    { id: 633, name: "Deino", types: ["dark", "dragon"], gen: 5, evolutions: 3 },
    { id: 634, name: "Zweilous", types: ["dark", "dragon"], gen: 5, evolutions: 3 },
    { id: 635, name: "Hydreigon", types: ["dark", "dragon"], gen: 5, evolutions: 3 },
    { id: 636, name: "Larvesta", types: ["bug", "fire"], gen: 5, evolutions: 2 },
    { id: 637, name: "Volcarona", types: ["bug", "fire"], gen: 5, evolutions: 2 },
    { id: 638, name: "Cobalion", types: ["steel", "fighting"], gen: 5, evolutions: 1 },
    { id: 639, name: "Terrakion", types: ["rock", "fighting"], gen: 5, evolutions: 1 },
    { id: 640, name: "Virizion", types: ["grass", "fighting"], gen: 5, evolutions: 1 },
    { id: 641, name: "Tornadus", types: ["flying"], gen: 5, evolutions: 1 },
    { id: 642, name: "Thundurus", types: ["electric", "flying"], gen: 5, evolutions: 1 },
    { id: 643, name: "Reshiram", types: ["dragon", "fire"], gen: 5, evolutions: 1 },
    { id: 644, name: "Zekrom", types: ["dragon", "electric"], gen: 5, evolutions: 1 },
    { id: 645, name: "Landorus", types: ["ground", "flying"], gen: 5, evolutions: 1 },
    { id: 646, name: "Kyurem", types: ["dragon", "ice"], gen: 5, evolutions: 1 },
    { id: 647, name: "Keldeo", types: ["water", "fighting"], gen: 5, evolutions: 1 },
    { id: 648, name: "Meloetta", types: ["normal", "psychic"], gen: 5, evolutions: 1 },
    { id: 649, name: "Genesect", types: ["bug", "steel"], gen: 5, evolutions: 1 },
    // === Generation 6 (Kalos) ===
    { id: 650, name: "Chespin", types: ["grass"], gen: 6, evolutions: 3 },
    { id: 651, name: "Quilladin", types: ["grass"], gen: 6, evolutions: 3 },
    { id: 652, name: "Chesnaught", types: ["grass", "fighting"], gen: 6, evolutions: 3 },
    { id: 653, name: "Fennekin", types: ["fire"], gen: 6, evolutions: 3 },
    { id: 654, name: "Braixen", types: ["fire"], gen: 6, evolutions: 3 },
    { id: 655, name: "Delphox", types: ["fire", "psychic"], gen: 6, evolutions: 3 },
    { id: 656, name: "Froakie", types: ["water"], gen: 6, evolutions: 3 },
    { id: 657, name: "Frogadier", types: ["water"], gen: 6, evolutions: 3 },
    { id: 658, name: "Greninja", types: ["water", "dark"], gen: 6, evolutions: 3 },
    { id: 659, name: "Bunnelby", types: ["normal"], gen: 6, evolutions: 2 },
    { id: 660, name: "Diggersby", types: ["normal", "ground"], gen: 6, evolutions: 2 },
    { id: 661, name: "Fletchling", types: ["normal", "flying"], gen: 6, evolutions: 3 },
    { id: 662, name: "Fletchinder", types: ["fire", "flying"], gen: 6, evolutions: 3 },
    { id: 663, name: "Talonflame", types: ["fire", "flying"], gen: 6, evolutions: 3 },
    { id: 664, name: "Scatterbug", types: ["bug"], gen: 6, evolutions: 3 },
    { id: 665, name: "Spewpa", types: ["bug"], gen: 6, evolutions: 3 },
    { id: 666, name: "Vivillon", types: ["bug", "flying"], gen: 6, evolutions: 3 },
    { id: 667, name: "Litleo", types: ["fire", "normal"], gen: 6, evolutions: 2 },
    { id: 668, name: "Pyroar", types: ["fire", "normal"], gen: 6, evolutions: 2 },
    { id: 669, name: "Flabébé", types: ["fairy"], gen: 6, evolutions: 3 },
    { id: 670, name: "Floette", types: ["fairy"], gen: 6, evolutions: 3 },
    { id: 671, name: "Florges", types: ["fairy"], gen: 6, evolutions: 3 },
    { id: 672, name: "Skiddo", types: ["grass"], gen: 6, evolutions: 2 },
    { id: 673, name: "Gogoat", types: ["grass"], gen: 6, evolutions: 2 },
    { id: 674, name: "Pancham", types: ["fighting"], gen: 6, evolutions: 2 },
    { id: 675, name: "Pangoro", types: ["fighting", "dark"], gen: 6, evolutions: 2 },
    { id: 676, name: "Furfrou", types: ["normal"], gen: 6, evolutions: 1 },
    { id: 677, name: "Espurr", types: ["psychic"], gen: 6, evolutions: 2 },
    { id: 678, name: "Meowstic", types: ["psychic"], gen: 6, evolutions: 2 },
    { id: 679, name: "Honedge", types: ["steel", "ghost"], gen: 6, evolutions: 3 },
    { id: 680, name: "Doublade", types: ["steel", "ghost"], gen: 6, evolutions: 3 },
    { id: 681, name: "Aegislash", types: ["steel", "ghost"], gen: 6, evolutions: 3 },
    { id: 682, name: "Spritzee", types: ["fairy"], gen: 6, evolutions: 2 },
    { id: 683, name: "Aromatisse", types: ["fairy"], gen: 6, evolutions: 2 },
    { id: 684, name: "Swirlix", types: ["fairy"], gen: 6, evolutions: 2 },
    { id: 685, name: "Slurpuff", types: ["fairy"], gen: 6, evolutions: 2 },
    { id: 686, name: "Inkay", types: ["dark", "psychic"], gen: 6, evolutions: 2 },
    { id: 687, name: "Malamar", types: ["dark", "psychic"], gen: 6, evolutions: 2 },
    { id: 688, name: "Binacle", types: ["rock", "water"], gen: 6, evolutions: 2 },
    { id: 689, name: "Barbaracle", types: ["rock", "water"], gen: 6, evolutions: 2 },
    { id: 690, name: "Skrelp", types: ["poison", "water"], gen: 6, evolutions: 2 },
    { id: 691, name: "Dragalge", types: ["poison", "dragon"], gen: 6, evolutions: 2 },
    { id: 692, name: "Clauncher", types: ["water"], gen: 6, evolutions: 2 },
    { id: 693, name: "Clawitzer", types: ["water"], gen: 6, evolutions: 2 },
    { id: 694, name: "Helioptile", types: ["electric", "normal"], gen: 6, evolutions: 2 },
    { id: 695, name: "Heliolisk", types: ["electric", "normal"], gen: 6, evolutions: 2 },
    { id: 696, name: "Tyrunt", types: ["rock", "dragon"], gen: 6, evolutions: 2 },
    { id: 697, name: "Tyrantrum", types: ["rock", "dragon"], gen: 6, evolutions: 2 },
    { id: 698, name: "Amaura", types: ["rock", "ice"], gen: 6, evolutions: 2 },
    { id: 699, name: "Aurorus", types: ["rock", "ice"], gen: 6, evolutions: 2 },
    { id: 700, name: "Sylveon", types: ["fairy"], gen: 6, evolutions: 2 },
    { id: 701, name: "Hawlucha", types: ["fighting", "flying"], gen: 6, evolutions: 1 },
    { id: 702, name: "Dedenne", types: ["electric", "fairy"], gen: 6, evolutions: 1 },
    { id: 703, name: "Carbink", types: ["rock", "fairy"], gen: 6, evolutions: 1 },
    { id: 704, name: "Goomy", types: ["dragon"], gen: 6, evolutions: 3 },
    { id: 705, name: "Sliggoo", types: ["dragon"], gen: 6, evolutions: 3 },
    { id: 706, name: "Goodra", types: ["dragon"], gen: 6, evolutions: 3 },
    { id: 707, name: "Klefki", types: ["steel", "fairy"], gen: 6, evolutions: 1 },
    { id: 708, name: "Phantump", types: ["ghost", "grass"], gen: 6, evolutions: 2 },
    { id: 709, name: "Trevenant", types: ["ghost", "grass"], gen: 6, evolutions: 2 },
    { id: 710, name: "Pumpkaboo", types: ["ghost", "grass"], gen: 6, evolutions: 2 },
    { id: 711, name: "Gourgeist", types: ["ghost", "grass"], gen: 6, evolutions: 2 },
    { id: 712, name: "Bergmite", types: ["ice"], gen: 6, evolutions: 2 },
    { id: 713, name: "Avalugg", types: ["ice"], gen: 6, evolutions: 2 },
    { id: 714, name: "Noibat", types: ["flying", "dragon"], gen: 6, evolutions: 2 },
    { id: 715, name: "Noivern", types: ["flying", "dragon"], gen: 6, evolutions: 2 },
    { id: 716, name: "Xerneas", types: ["fairy"], gen: 6, evolutions: 1 },
    { id: 717, name: "Yveltal", types: ["dark", "flying"], gen: 6, evolutions: 1 },
    { id: 719, name: "Diancie", types: ["rock", "fairy"], gen: 6, evolutions: 1 },
    { id: 720, name: "Hoopa", types: ["psychic", "ghost"], gen: 6, evolutions: 1 },
    { id: 721, name: "Volcanion", types: ["fire", "water"], gen: 6, evolutions: 1 },
    // === Generation 7 (Alola) ===
    { id: 722, name: "Rowlet", types: ["grass", "flying"], gen: 7, evolutions: 3 },
    { id: 723, name: "Dartrix", types: ["grass", "flying"], gen: 7, evolutions: 3 },
    { id: 724, name: "Decidueye", types: ["grass", "ghost"], gen: 7, evolutions: 3 },
    { id: 725, name: "Litten", types: ["fire"], gen: 7, evolutions: 3 },
    { id: 726, name: "Torracat", types: ["fire"], gen: 7, evolutions: 3 },
    { id: 727, name: "Incineroar", types: ["fire", "dark"], gen: 7, evolutions: 3 },
    { id: 728, name: "Popplio", types: ["water"], gen: 7, evolutions: 3 },
    { id: 729, name: "Brionne", types: ["water"], gen: 7, evolutions: 3 },
    { id: 730, name: "Primarina", types: ["water", "fairy"], gen: 7, evolutions: 3 },
    { id: 731, name: "Pikipek", types: ["normal", "flying"], gen: 7, evolutions: 3 },
    { id: 732, name: "Trumbeak", types: ["normal", "flying"], gen: 7, evolutions: 3 },
    { id: 733, name: "Toucannon", types: ["normal", "flying"], gen: 7, evolutions: 3 },
    { id: 734, name: "Yungoos", types: ["normal"], gen: 7, evolutions: 2 },
    { id: 735, name: "Gumshoos", types: ["normal"], gen: 7, evolutions: 2 },
    { id: 736, name: "Grubbin", types: ["bug"], gen: 7, evolutions: 3 },
    { id: 737, name: "Charjabug", types: ["bug", "electric"], gen: 7, evolutions: 3 },
    { id: 738, name: "Vikavolt", types: ["bug", "electric"], gen: 7, evolutions: 3 },
    { id: 739, name: "Crabrawler", types: ["fighting"], gen: 7, evolutions: 2 },
    { id: 740, name: "Crabominable", types: ["fighting", "ice"], gen: 7, evolutions: 2 },
    { id: 741, name: "Oricorio", types: ["fire", "flying"], gen: 7, evolutions: 1 },
    { id: 742, name: "Cutiefly", types: ["bug", "fairy"], gen: 7, evolutions: 2 },
    { id: 743, name: "Ribombee", types: ["bug", "fairy"], gen: 7, evolutions: 2 },
    { id: 744, name: "Rockruff", types: ["rock"], gen: 7, evolutions: 2 },
    { id: 745, name: "Lycanroc", types: ["rock"], gen: 7, evolutions: 2 },
    { id: 746, name: "Wishiwashi", types: ["water"], gen: 7, evolutions: 1 },
    { id: 747, name: "Mareanie", types: ["poison", "water"], gen: 7, evolutions: 2 },
    { id: 748, name: "Toxapex", types: ["poison", "water"], gen: 7, evolutions: 2 },
    { id: 749, name: "Mudbray", types: ["ground"], gen: 7, evolutions: 2 },
    { id: 750, name: "Mudsdale", types: ["ground"], gen: 7, evolutions: 2 },
    { id: 751, name: "Dewpider", types: ["water", "bug"], gen: 7, evolutions: 2 },
    { id: 752, name: "Araquanid", types: ["water", "bug"], gen: 7, evolutions: 2 },
    { id: 753, name: "Fomantis", types: ["grass"], gen: 7, evolutions: 2 },
    { id: 754, name: "Lurantis", types: ["grass"], gen: 7, evolutions: 2 },
    { id: 755, name: "Morelull", types: ["grass", "fairy"], gen: 7, evolutions: 2 },
    { id: 756, name: "Shiinotic", types: ["grass", "fairy"], gen: 7, evolutions: 2 },
    { id: 757, name: "Salandit", types: ["poison", "fire"], gen: 7, evolutions: 2 },
    { id: 758, name: "Salazzle", types: ["poison", "fire"], gen: 7, evolutions: 2 },
    { id: 759, name: "Stufful", types: ["normal", "fighting"], gen: 7, evolutions: 2 },
    { id: 760, name: "Bewear", types: ["normal", "fighting"], gen: 7, evolutions: 2 },
    { id: 761, name: "Bounsweet", types: ["grass"], gen: 7, evolutions: 3 },
    { id: 762, name: "Steenee", types: ["grass"], gen: 7, evolutions: 3 },
    { id: 763, name: "Tsareena", types: ["grass"], gen: 7, evolutions: 3 },
    { id: 764, name: "Comfey", types: ["fairy"], gen: 7, evolutions: 1 },
    { id: 765, name: "Oranguru", types: ["normal", "psychic"], gen: 7, evolutions: 1 },
    { id: 766, name: "Passimian", types: ["fighting"], gen: 7, evolutions: 1 },
    { id: 767, name: "Wimpod", types: ["bug", "water"], gen: 7, evolutions: 2 },
    { id: 768, name: "Golisopod", types: ["bug", "water"], gen: 7, evolutions: 2 },
    { id: 769, name: "Sandygast", types: ["ghost", "ground"], gen: 7, evolutions: 2 },
    { id: 770, name: "Palossand", types: ["ghost", "ground"], gen: 7, evolutions: 2 },
    { id: 771, name: "Pyukumuku", types: ["water"], gen: 7, evolutions: 1 },
    { id: 772, name: "Type: Null", types: ["normal"], gen: 7, evolutions: 2 },
    { id: 773, name: "Silvally", types: ["normal"], gen: 7, evolutions: 2 },
    { id: 774, name: "Minior", types: ["rock", "flying"], gen: 7, evolutions: 1 },
    { id: 775, name: "Komala", types: ["normal"], gen: 7, evolutions: 1 },
    { id: 776, name: "Turtonator", types: ["fire", "dragon"], gen: 7, evolutions: 1 },
    { id: 777, name: "Togedemaru", types: ["electric", "steel"], gen: 7, evolutions: 1 },
    { id: 778, name: "Mimikyu", types: ["ghost", "fairy"], gen: 7, evolutions: 1 },
    { id: 779, name: "Bruxish", types: ["water", "psychic"], gen: 7, evolutions: 1 },
    { id: 780, name: "Drampa", types: ["normal", "dragon"], gen: 7, evolutions: 1 },
    { id: 781, name: "Dhelmise", types: ["ghost", "grass"], gen: 7, evolutions: 1 },
    { id: 782, name: "Jangmo-o", types: ["dragon"], gen: 7, evolutions: 3 },
    { id: 783, name: "Hakamo-o", types: ["dragon", "fighting"], gen: 7, evolutions: 3 },
    { id: 784, name: "Kommo-o", types: ["dragon", "fighting"], gen: 7, evolutions: 3 },
    { id: 785, name: "Tapu Koko", types: ["electric", "fairy"], gen: 7, evolutions: 1 },
    { id: 786, name: "Tapu Lele", types: ["psychic", "fairy"], gen: 7, evolutions: 1 },
    { id: 787, name: "Tapu Bulu", types: ["grass", "fairy"], gen: 7, evolutions: 1 },
    { id: 788, name: "Tapu Fini", types: ["water", "fairy"], gen: 7, evolutions: 1 },
    { id: 789, name: "Cosmog", types: ["psychic"], gen: 7, evolutions: 3 },
    { id: 790, name: "Cosmoem", types: ["psychic"], gen: 7, evolutions: 3 },
    { id: 791, name: "Solgaleo", types: ["psychic", "steel"], gen: 7, evolutions: 3 },
    { id: 792, name: "Lunala", types: ["psychic", "ghost"], gen: 7, evolutions: 3 },
    { id: 793, name: "Nihilego", types: ["rock", "poison"], gen: 7, evolutions: 1 },
    { id: 794, name: "Buzzwole", types: ["bug", "fighting"], gen: 7, evolutions: 1 },
    { id: 795, name: "Pheromosa", types: ["bug", "fighting"], gen: 7, evolutions: 1 },
    { id: 796, name: "Xurkitree", types: ["electric"], gen: 7, evolutions: 1 },
    { id: 797, name: "Celesteela", types: ["steel", "flying"], gen: 7, evolutions: 1 },
    { id: 798, name: "Kartana", types: ["grass", "steel"], gen: 7, evolutions: 1 },
    { id: 799, name: "Guzzlord", types: ["dark", "dragon"], gen: 7, evolutions: 1 },
    { id: 800, name: "Necrozma", types: ["psychic"], gen: 7, evolutions: 1 },
    { id: 801, name: "Magearna", types: ["steel", "fairy"], gen: 7, evolutions: 1 },
    { id: 802, name: "Marshadow", types: ["fighting", "ghost"], gen: 7, evolutions: 1 },
    { id: 803, name: "Poipole", types: ["poison"], gen: 7, evolutions: 2 },
    { id: 804, name: "Naganadel", types: ["poison", "dragon"], gen: 7, evolutions: 2 },
    { id: 805, name: "Stakataka", types: ["rock", "steel"], gen: 7, evolutions: 1 },
    { id: 806, name: "Blacephalon", types: ["fire", "ghost"], gen: 7, evolutions: 1 },
    { id: 807, name: "Zeraora", types: ["electric"], gen: 7, evolutions: 1 },
    { id: 808, name: "Meltan", types: ["steel"], gen: 7, evolutions: 2 },
    { id: 809, name: "Melmetal", types: ["steel"], gen: 7, evolutions: 2 },
    // === Generation 8 (Galar) ===
    { id: 810, name: "Grookey", types: ["grass"], gen: 8, evolutions: 3 },
    { id: 811, name: "Thwackey", types: ["grass"], gen: 8, evolutions: 3 },
    { id: 812, name: "Rillaboom", types: ["grass"], gen: 8, evolutions: 3 },
    { id: 813, name: "Scorbunny", types: ["fire"], gen: 8, evolutions: 3 },
    { id: 814, name: "Raboot", types: ["fire"], gen: 8, evolutions: 3 },
    { id: 815, name: "Cinderace", types: ["fire"], gen: 8, evolutions: 3 },
    { id: 816, name: "Sobble", types: ["water"], gen: 8, evolutions: 3 },
    { id: 817, name: "Drizzile", types: ["water"], gen: 8, evolutions: 3 },
    { id: 818, name: "Inteleon", types: ["water"], gen: 8, evolutions: 3 },
    { id: 819, name: "Skwovet", types: ["normal"], gen: 8, evolutions: 2 },
    { id: 820, name: "Greedent", types: ["normal"], gen: 8, evolutions: 2 },
    { id: 821, name: "Rookidee", types: ["flying"], gen: 8, evolutions: 3 },
    { id: 822, name: "Corvisquire", types: ["flying"], gen: 8, evolutions: 3 },
    { id: 823, name: "Corviknight", types: ["flying", "steel"], gen: 8, evolutions: 3 },
    { id: 824, name: "Blipbug", types: ["bug"], gen: 8, evolutions: 3 },
    { id: 825, name: "Dottler", types: ["bug", "psychic"], gen: 8, evolutions: 3 },
    { id: 826, name: "Orbeetle", types: ["bug", "psychic"], gen: 8, evolutions: 3 },
    { id: 827, name: "Nickit", types: ["dark"], gen: 8, evolutions: 2 },
    { id: 828, name: "Thievul", types: ["dark"], gen: 8, evolutions: 2 },
    { id: 829, name: "Gossifleur", types: ["grass"], gen: 8, evolutions: 2 },
    { id: 830, name: "Eldegoss", types: ["grass"], gen: 8, evolutions: 2 },
    { id: 831, name: "Wooloo", types: ["normal"], gen: 8, evolutions: 2 },
    { id: 832, name: "Dubwool", types: ["normal"], gen: 8, evolutions: 2 },
    { id: 833, name: "Chewtle", types: ["water"], gen: 8, evolutions: 2 },
    { id: 834, name: "Drednaw", types: ["water", "rock"], gen: 8, evolutions: 2 },
    { id: 835, name: "Yamper", types: ["electric"], gen: 8, evolutions: 2 },
    { id: 836, name: "Boltund", types: ["electric"], gen: 8, evolutions: 2 },
    { id: 837, name: "Rolycoly", types: ["rock"], gen: 8, evolutions: 3 },
    { id: 838, name: "Carkol", types: ["rock", "fire"], gen: 8, evolutions: 3 },
    { id: 839, name: "Coalossal", types: ["rock", "fire"], gen: 8, evolutions: 3 },
    { id: 840, name: "Applin", types: ["grass", "dragon"], gen: 8, evolutions: 2 },
    { id: 841, name: "Flapple", types: ["grass", "dragon"], gen: 8, evolutions: 2 },
    { id: 842, name: "Appletun", types: ["grass", "dragon"], gen: 8, evolutions: 2 },
    { id: 843, name: "Silicobra", types: ["ground"], gen: 8, evolutions: 2 },
    { id: 844, name: "Sandaconda", types: ["ground"], gen: 8, evolutions: 2 },
    { id: 845, name: "Cramorant", types: ["flying", "water"], gen: 8, evolutions: 1 },
    { id: 846, name: "Arrokuda", types: ["water"], gen: 8, evolutions: 2 },
    { id: 847, name: "Barraskewda", types: ["water"], gen: 8, evolutions: 2 },
    { id: 848, name: "Toxel", types: ["electric", "poison"], gen: 8, evolutions: 2 },
    { id: 849, name: "Toxtricity", types: ["electric", "poison"], gen: 8, evolutions: 2 },
    { id: 850, name: "Sizzlipede", types: ["fire", "bug"], gen: 8, evolutions: 2 },
    { id: 851, name: "Centiskorch", types: ["fire", "bug"], gen: 8, evolutions: 2 },
    { id: 852, name: "Clobbopus", types: ["fighting"], gen: 8, evolutions: 2 },
    { id: 853, name: "Grapploct", types: ["fighting", "water"], gen: 8, evolutions: 2 },
    { id: 854, name: "Sinistea", types: ["ghost"], gen: 8, evolutions: 2 },
    { id: 855, name: "Polteageist", types: ["ghost"], gen: 8, evolutions: 2 },
    { id: 856, name: "Hatenna", types: ["psychic"], gen: 8, evolutions: 3 },
    { id: 857, name: "Hattrem", types: ["psychic"], gen: 8, evolutions: 3 },
    { id: 858, name: "Hatterene", types: ["psychic", "fairy"], gen: 8, evolutions: 3 },
    { id: 859, name: "Impidimp", types: ["dark", "fairy"], gen: 8, evolutions: 3 },
    { id: 860, name: "Morgrem", types: ["dark", "fairy"], gen: 8, evolutions: 3 },
    { id: 861, name: "Grimmsnarl", types: ["dark", "fairy"], gen: 8, evolutions: 3 },
    { id: 862, name: "Obstagoon", types: ["dark", "normal"], gen: 8, evolutions: 3 },
    { id: 863, name: "Perrserker", types: ["steel"], gen: 8, evolutions: 2 },
    { id: 864, name: "Cursola", types: ["ghost"], gen: 8, evolutions: 2 },
    { id: 865, name: "Sirfetch’d", types: ["fighting"], gen: 8, evolutions: 1 },
    { id: 866, name: "Mr. Rime", types: ["ice", "psychic"], gen: 8, evolutions: 2 },
    { id: 867, name: "Runerigus", types: ["ground", "ghost"], gen: 8, evolutions: 2 },
    { id: 868, name: "Milcery", types: ["fairy"], gen: 8, evolutions: 2 },
    { id: 869, name: "Alcremie", types: ["fairy"], gen: 8, evolutions: 2 },
    { id: 870, name: "Falinks", types: ["fighting"], gen: 8, evolutions: 1 },
    { id: 871, name: "Pincurchin", types: ["electric"], gen: 8, evolutions: 1 },
    { id: 872, name: "Snom", types: ["ice", "bug"], gen: 8, evolutions: 2 },
    { id: 873, name: "Frosmoth", types: ["ice", "bug"], gen: 8, evolutions: 2 },
    { id: 874, name: "Stonjourner", types: ["rock"], gen: 8, evolutions: 1 },
    { id: 875, name: "Eiscue", types: ["ice"], gen: 8, evolutions: 1 },
    { id: 876, name: "Indeedee", types: ["psychic", "normal"], gen: 8, evolutions: 1 },
    { id: 877, name: "Morpeko", types: ["electric", "dark"], gen: 8, evolutions: 1 },
    { id: 878, name: "Cufant", types: ["steel"], gen: 8, evolutions: 2 },
    { id: 879, name: "Copperajah", types: ["steel"], gen: 8, evolutions: 2 },
    { id: 880, name: "Dracozolt", types: ["electric", "dragon"], gen: 8, evolutions: 1 },
    { id: 881, name: "Arctozolt", types: ["electric", "ice"], gen: 8, evolutions: 1 },
    { id: 882, name: "Dracovish", types: ["water", "dragon"], gen: 8, evolutions: 1 },
    { id: 883, name: "Arctovish", types: ["water", "ice"], gen: 8, evolutions: 1 },
    { id: 884, name: "Duraludon", types: ["steel", "dragon"], gen: 8, evolutions: 1 },
    { id: 885, name: "Dreepy", types: ["dragon", "ghost"], gen: 8, evolutions: 3 },
    { id: 886, name: "Drakloak", types: ["dragon", "ghost"], gen: 8, evolutions: 3 },
    { id: 887, name: "Dragapult", types: ["dragon", "ghost"], gen: 8, evolutions: 3 },
    { id: 888, name: "Zacian", types: ["fairy"], gen: 8, evolutions: 1 },
    { id: 889, name: "Zamazenta", types: ["fighting"], gen: 8, evolutions: 1 },
    { id: 890, name: "Eternatus", types: ["poison", "dragon"], gen: 8, evolutions: 1 },
    { id: 891, name: "Kubfu", types: ["fighting"], gen: 8, evolutions: 2 },
    { id: 893, name: "Zarude", types: ["dark", "grass"], gen: 8, evolutions: 1 },
    { id: 894, name: "Regieleki", types: ["electric"], gen: 8, evolutions: 1 },
    { id: 895, name: "Regidrago", types: ["dragon"], gen: 8, evolutions: 1 },
    { id: 896, name: "Glastrier", types: ["ice"], gen: 8, evolutions: 1 },
    { id: 897, name: "Spectrier", types: ["ghost"], gen: 8, evolutions: 1 },
    { id: 898, name: "Calyrex", types: ["psychic", "grass"], gen: 8, evolutions: 1 },
];
